### ISSUE TITLE
NAC is broken in development branch?

### ISSUE THREAD

**Issue by akentphonon** [phonopy/phonopy#112]
it seems that NAC is broken in the development branch. Even when the BORN file is present in the current directory, phonopy gives the error:

   if nac_params is None and file_exists("BORN", log_level):
NameError: name 'nac_params' is not defined

I am using phonopy via command line:

phonopy -p --readfc --band=auto --dim="6 6 6" -c POSCAR-unitcell --readfc-format=HDF5 --band-connection --nac

**Comment by atztogo** [comment]
Thanks. I think this is fixed.
But there may be other issues. Today, I refactored phonopy code around the user interface.

**Comment by akentphonon** [comment]
Thanks! Now it works properly.

If I find any other issues, I will notify you.


Thanks
Alex
