### ISSUE TITLE
FHI-aims example is broken

### ISSUE THREAD

**Issue by Kokookster** [phonopy/phonopy#114]
By running the FHI-aims example (`example/diamond-FHI-aims`) I realized that it is not working anymore. (I am using the current development branch.) It throws: `"BORN" was not found.`, although neither nac or Born was requested. I think it is due to line 826 and 850 in `scripts/phonopy`. Changing `or` to `and` in line 826 fixes it for the FHI-aims example, but not sure if this breaks other parts.

**Comment by atztogo** [comment]
Thanks, @Kokookster. You are correct. This was due to my recent change of the code. I fixed this. But this fix may have side effect. The test of the user interface is uneasy (i.e., phonopy is not written well considering test). Currently test is only possible by reports from users, like this issue.

**Comment by atztogo** [comment]
I close this issue because this is fixed.

**Comment by Kokookster** [comment]
Many thanks for fixing it!
