### ISSUE TITLE
assert in c/_spglib.c

### ISSUE THREAD

**Issue by nanoflow** [phonopy/phonopy#115]
Comparing to https://github.com/atztogo/spglib/issues/78 line 394 in c/_spglib.c has to be changed to 
  assert(n == len_list);

**Comment by atztogo** [comment]
Thanks for your report. This is fixed at https://github.com/atztogo/spglib/commit/d57070831585a6f02dec0a31d25b375ba347798c. So this version of spglib has been included at https://github.com/phonopy/phonopy/commit/bb700a3e1fb24dcabe10227bea4da0a1f9334ae2.

**Comment by atztogo** [comment]
This is fixed. I close this issue.
