### ISSUE TITLE
Missing Intel libraries when building from source

### ISSUE THREAD

**Issue by mcaroba** [phonopy/phonopy#123]
I'm trying to install Phonopy from source on a cluster machine, and because of some other stuff, I'm stuck with icc as C compiler in os.environ. This leads to an error when importing _spglib, in particular the _intel_fast_memcpy library is not retrievable. This can be fixed by adding an explicit definition for the LDSHARED environment variable to the setup command:

LDSHARED="icc -shared" python3 setup.py install

Maybe this is useful to someone with the same problem as me.

**Comment by atztogo** [comment]
Thanks for your information. I put a link to here from the documentation,
https://phonopy.github.io/phonopy/install.html#missing-intel-libraries-when-building-from-source-using-icc

I close this issue, but this issue is expected to be reopened whenever necessary.

**Comment by PMG29** [comment]
I am new to phono3py.Please help me to solve following error when i use this command-
phono3py --mesh="20 20 20" --fc3 --fc2 --br
Error:
ImportError: /home/physics/.local/lib/python3.8/site-packages/phono3py/_phono3py.cpython-38-x86_64-linux-gnu.so: undefined symbol: LAPACKE_dsyev
Kindly give your valuable inputs.

**Comment by atztogo** [comment]
@PMG29, please send your question to the phonopy mailing list.

**Comment by PMG29** [comment]
Respected Sir,
Thank you for your response.
Can you provide details solution for my problem,because I am new to phonopy
and not able to solve the problem.please help me to solve this problem.

Thanks & Regards

Pratik Gadhavi
