### ISSUE TITLE
How to get the frequency, eigenvector and the derivative of dynamical matrix at a specific q-point and a branch index

### ISSUE THREAD

**Issue by ZengZezhu** [phonopy/phonopy#124]
Dear Professor,

I want to obtain the frequency, eigenvectors and the derivative of dynamical matrix at a specific q-point with a specific branch index(the derivative of dynamical matrix is independent with the branch).  

I try to read the code of phonopy, but I still have no any ideas how to obtain these properties quickly. Actually I need a complete information about the frequency, eigenvector, and the derivative of dynamical matrix at all q-points with all branches. Could you have any suggestions to help me to start this work?

Best,
Zezhu

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.

**Comment by ZengZezhu** [comment]
Hi, professor.

I cannot read the reply from you at sourceforge, sorry I am not familiar with it.

**Comment by atztogo** [comment]
Please subscribe from here and send question to the mailing list address from the e-mail address that you subscribe
https://sourceforge.net/projects/phonopy/lists/phonopy-users
