### ISSUE TITLE
Test fail on conda-forge build for pypy

### ISSUE THREAD

**Issue by jochym** [phonopy/phonopy#129]
It seems we are quite close to having a functional build for pypy on conda-forge. There are actually two tests that fail: `test_parse_vasprun_xml (interface.test_vasp.TestVASP)` and `testPhonopy (test_api_phonopy.TestPhonopy)`. The errors are the same on linux and OSX so this seems like something non-random and not connected with the OS. Maybe we can fix this? 

Here is a full test report:
```
+ python -m unittest discover -b
......s.........E..............................................F
======================================================================
ERROR: test_parse_vasprun_xml (interface.test_vasp.TestVASP)
----------------------------------------------------------------------
TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/test_tmp/test/interface/test_vasp.py", line 46, in test_parse_vasprun_xml
    np.testing.assert_allclose(ref, vr.read_forces(), atol=1e-8)
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/site-packages/phonopy/interface/vasp.py", line 511, in read_forces
    return self._parse_expat_vasprun_xml()
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/site-packages/phonopy/interface/vasp.py", line 607, in _parse_expat_vasprun_xml
    return self._parse_by_expat(self._fileptr)
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/site-packages/phonopy/interface/vasp.py", line 620, in _parse_by_expat
    return vasprun.get_forces()[-1]
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/site-packages/phonopy/interface/vasp.py", line 729, in get_forces
    return self.forces
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/site-packages/phonopy/interface/vasp.py", line 726, in forces
    return np.array(self._all_forces, dtype='double', order='C')
ValueError: setting an array element with a sequence.

======================================================================
FAIL: testPhonopy (test_api_phonopy.TestPhonopy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/phonopy_1601022451156/test_tmp/test/test_api_phonopy.py", line 34, in testPhonopy
    == id(phonon.get_displacements()))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 64 tests in 111.567s

FAILED (failures=1, errors=1, skipped=1)

```

**Comment by atztogo** [comment]
Thanks for your work!

> ERROR: test_parse_vasprun_xml (interface.test_vasp.TestVASP)

I can't see why it gives this error. In the test, text files of `vasprun.xml-001` and `vasprun.xml-002` are extracted from `vasprun.xml.tar.bz2` using `tarfile` python standard module., then they are parsed using `xml.parsers.expat` python standard module. The code that I wrote to parse them can have a bug, but I want to see what happens by running the test for the extracted files without using `tarfile`.

> FAIL: testPhonopy (test_api_phonopy.TestPhonopy)

I think this can fail, and now this test is not important. I will remove it.

How can I proceed?

**Comment by jochym** [comment]
The problem may come from some parsing function which returns `['string']' instead of `'string'` or something of that sort. I have encountered such cases in the past. 

I can modify the test/coda/data on the fly. If you could provide commands to execute before the tests I can insert them temporarily to further diagnose the issue. You can also directly modify the PR (https://github.com/conda-forge/phonopy-feedstock/pull/80) on github by editing this part of `meta.yaml` file:
```yaml
test:
  imports:
    - phonopy
  source_files:
    - test
  commands:
    - pip check
    - cd test
    - rm phonon/test_random_displacements.py
    - python -m unittest discover -b
    - conda inspect linkages -p $PREFIX phonopy  # [not win]
    - conda inspect objects -p $PREFIX phonopy  # [osx]
```
every commit will run the tests so you can have quick turnaround. Tell me how can I help?

**Comment by atztogo** [comment]
I think `test_api_phonopy.py` can be safely removed.

It seems the vasprun.xml parser using `xml.parsers.expat` fails. In phonopy, there is another parser using `xml.etree.cElementTree`, which works. I don't know the reason. Maybe my code is badly written or `xml.parsers.expat` may have a potential problem in pypy, or it can be a container problem (memory overflow etc).

Replacing `xml.parsers.expat` by `xml.etree.cElementTree` can be workaround of the test, which can be switched by a keyword argument (`use_expat=False`).

So I think that the modification of `meta.yaml` below can be a temporal solution:
```
...
    - rm phonon/test_random_displacements.py
    - rm test_api_phonopy.py
    - sed s/use_expat=True/use_expat=False/ interface/test_vasp.py > interface/test_vasp_etree.py
    - rm interface/test_vasp.py
    - python -m unittest discover -b
...
```
(This has not been tested yet.)

I will update phonopy until the next release so that the vasprun.xml parser with `xml.etree.cElementTree` is used instead of that with `xml.parsers.expat` when the later fails, though the later is faster and more robust.

**Comment by jochym** [comment]
What about lxml? Should I look around for some xml parser recommendation?

**Comment by atztogo** [comment]
Thanks for your suggestion. But at this momemnt, I would like to avoid using lxml.

Phonopy used to use lxml in the old time. But I got a request not to use lxml (https://github.com/phonopy/phonopy/pull/3), so I replaced it to the standard module. It was very before and now it's OK to use lxml, but I hope to keep phonopy having less dependency. At least the built-in vasprun.xml parser with `xml.etree.cElementTree` works for PyPy, so I think we don't need to rush trying lxml. But as I wrote, I will update phonopy so as to fail-over to the parser with `xml.etree.cElementTree` when the parser with `xml.parsers.expat` failed. This will be done until the next release.

The disadvantage to use `xml.etree.cElementTree`  is that this consumes large memory space when vasprun.xml is large. This happens when the user runs with `LORBIT`. Some users seem setting `LORBIT` as default even for unnecessary cases. PyPy phonopy users seriously feel it as the problem, I will consider to use lxml, but then I would use parsevasp (https://github.com/aiida-vasp/parsevasp).

**Comment by jochym** [comment]
Less dependency is a worthy goal! Maybe we can reduce the memory consumption of the standard parser in the future. Not every XML parsing strategy is equal in this regard.

But returning to the present issue: maybe we can just fix the problem with current code by finding why the parser does not work properly on pypy. Would you point me to the offending part of code and test data. I will try to debug this issue locally. Maybe it is a problem with interfacing with `xml` module or some overlooked detail we can fix easily.

**Comment by atztogo** [comment]
> Maybe it is a problem with interfacing with xml module or some overlooked detail we can fix easily.

This is very possible. I may write the code in a very bad manner. But writing the parser with `xml.parsers.expat` was uneasy for me.

What I did with modifying `meta.yaml` was to set `use_expat=False` by replacing this line by sed:

https://github.com/phonopy/phonopy/blob/50378d49b4db85b72e3841623feb988bfcd451cf/test/interface/test_vasp.py#L41

Then the test passed. So I concluded the problem is probably in the vasprun.xml parser with `xml.parsers.expat`. I didn't do any more investigation.

`class Vasprun` is the wrapper of the parsers with `xml.parsers.expat` and `xml.etree.cElementTree`.

https://github.com/phonopy/phonopy/blob/50378d49b4db85b72e3841623feb988bfcd451cf/phonopy/interface/vasp.py#L504

**Comment by jochym** [comment]
Thanks. I needed confirmation of my own analysis. I guess you are testing on the xml file from test directory? I will do some tests and report on my conclusions.

**Comment by atztogo** [comment]
Thanks.

I first doubted the extraction from bz2 file in PyPy:

https://github.com/phonopy/phonopy/blob/50378d49b4db85b72e3841623feb988bfcd451cf/test/interface/test_vasp.py#L37

but this was OK. I mean, this commit gives the test failure,

https://github.com/conda-forge/phonopy-feedstock/pull/80/commits/532fe6431ffe575213ca6379ed93dff40b0dde83

Then by the following commit, this test passed,

https://github.com/conda-forge/phonopy-feedstock/pull/80/commits/3fd7aac8f9ea3dcfb53dad254e92c3d85519ee57

**Comment by jochym** [comment]
I have found at least a clue. After parsing `vasprun.xml-001` the `self._all_forces` list contains two lines which are short (2 instead of 3 numbers):
```python
for n, l in enumerate(vrx._all_forces[0]):
     if len(l) != 3:
         print(f'{n}:', l)
 
8: [-0.00057168, -0.0]
9: [212.0, -2.12e-06]
```
I do not know what is wrong with the parser but processing of vector data has some subtle problem.
Here is the data:
```xml
  <varray name="forces" >
   <v>      -0.01806194       0.00000000       0.00000000 </v>
   <v>       0.00302404       0.00000000       0.00000000 </v>
   <v>      -0.00004340       0.00000000       0.00000000 </v>
   <v>       0.00010669       0.00000000       0.00000000 </v>
   <v>      -0.00004340       0.00000000       0.00000000 </v>
   <v>       0.00010669       0.00000000       0.00000000 </v>
   <v>      -0.00015899       0.00000000       0.00000000 </v>
   <v>       0.00013442       0.00000000       0.00000000 </v>
   <v>      -0.00057168      -0.00000212      -0.00000212 </v>
   <v>       0.00038176       0.00000024       0.00000024 </v>
   <v>      -0.00057168       0.00000212      -0.00000212 </v>
   <v>       0.00038176      -0.00000024       0.00000024 </v>
   <v>      -0.00057168      -0.00000212       0.00000212 </v>
   <v>       0.00038176       0.00000024      -0.00000024 </v>
   <v>      -0.00057168       0.00000212       0.00000212 </v>
   <v>       0.00038176      -0.00000024      -0.00000024 </v>
   <v>       0.00048457       0.00000000       0.00193549 </v>
   <v>       0.00048501       0.00000000      -0.00192143 </v>
   <v>      -0.00001838       0.00000000      -0.00001788 </v>
   <v>      -0.00001737       0.00000000       0.00001704 </v>
   <v>       0.00048457       0.00000000      -0.00193549 </v>
   <v>       0.00048501       0.00000000       0.00192143 </v>
   <v>      -0.00001838       0.00000000       0.00001788 </v>
   <v>      -0.00001737       0.00000000      -0.00001704 </v>
   <v>       0.00048457       0.00193549       0.00000000 </v>
   <v>       0.00048501      -0.00192143       0.00000000 </v>
   <v>       0.00048457      -0.00193549       0.00000000 </v>
   <v>       0.00048501       0.00192143       0.00000000 </v>
   <v>      -0.00001838      -0.00001788       0.00000000 </v>
   <v>      -0.00001737       0.00001704       0.00000000 </v>
   <v>      -0.00001838       0.00001788       0.00000000 </v>
   <v>      -0.00001737      -0.00001704       0.00000000 </v>
   <v>      -0.00008108      -0.00042820      -0.00042820 </v>
   <v>      -0.00008351       0.00042588       0.00042588 </v>
   <v>      -0.00008108       0.00042820      -0.00042820 </v>
   <v>      -0.00008351      -0.00042588       0.00042588 </v>
   <v>      -0.00008108      -0.00042820       0.00042820 </v>
   <v>      -0.00008351       0.00042588      -0.00042588 </v>
   <v>      -0.00008108       0.00042820       0.00042820 </v>
   <v>      -0.00008351      -0.00042588      -0.00042588 </v>
   <v>       0.00502017       0.00000000       0.00000000 </v>
   <v>       0.00461404       0.00000000       0.00000000 </v>
   <v>       0.00004083       0.00000000       0.00000000 </v>
   <v>       0.00003737       0.00000000       0.00000000 </v>
   <v>       0.00004083       0.00000000       0.00000000 </v>
   <v>       0.00003737       0.00000000       0.00000000 </v>
   <v>      -0.00001053       0.00000000       0.00000000 </v>
   <v>      -0.00001180       0.00000000       0.00000000 </v>
   <v>       0.00171488      -0.00001102       0.00000000 </v>
   <v>      -0.00096003      -0.00000136       0.00000000 </v>
   <v>       0.00171488       0.00001102       0.00000000 </v>
   <v>      -0.00096003       0.00000136       0.00000000 </v>
   <v>       0.00019361       0.00000118       0.00000000 </v>
   <v>      -0.00023590       0.00000009       0.00000000 </v>
   <v>       0.00019361      -0.00000118       0.00000000 </v>
   <v>      -0.00023590      -0.00000009       0.00000000 </v>
   <v>       0.00171488       0.00000000      -0.00001102 </v>
   <v>      -0.00096003       0.00000000      -0.00000136 </v>
   <v>       0.00019361       0.00000000       0.00000118 </v>
   <v>      -0.00023590       0.00000000       0.00000009 </v>
   <v>       0.00171488       0.00000000       0.00001102 </v>
   <v>      -0.00096003       0.00000000       0.00000136 </v>
   <v>       0.00019361       0.00000000      -0.00000118 </v>
   <v>      -0.00023590       0.00000000      -0.00000009 </v>
  </varray>
```
I see no obvious problems with it.

**Comment by jochym** [comment]
I think I found the problem. The continuity of the data is not guaranteed in expat even if you use `buffer_text = True`. It simply worked by luck in other interpreters. I think you are supposed to collect the data for the element and process it in `_end_element` callback. Unfortunately this may show up in other places so I would recommend changing this implementation. I can help a little since I have written some state machines (e.g. OUTCAR parser) in the past.

**Comment by atztogo** [comment]
Due to my lack of my knowledge, I don't understand well what you wrote. The parser seems getting two strings of `"-0.00057168      -0.00000"` and `"212      -0.00000212"` in one line. How does this happen? Running in multhread?

**Comment by atztogo** [comment]
Maybe do I have to collect strings and concatenate them when `EndElementHandler` is called?

**Comment by atztogo** [comment]
Common Pitfalls: https://libexpat.github.io/doc/common-pitfalls/#split-character-data

**Comment by atztogo** [comment]
@jochym , if you can test `fix-expat` branch, could you see if it works or not by your PyPy environment?

**Comment by jochym** [comment]
I will. I am in the meeting right now but I will get back to you.

**Comment by jochym** [comment]
I think that your approach is correct. Collect the data and parse it at `_end_element`.
The code runs properly on pypy. Maybe new release will be in order?

**Comment by atztogo** [comment]
Thank you very much for your confirmation. Then, I will release v2.8.1 tomorrow. Is it OK?

**Comment by jochym** [comment]
Great. The pypy release can wait for a new version.

**Comment by atztogo** [comment]
@jochym, can this issue be closed?

**Comment by atztogo** [comment]
Maybe this issue can be closed. Please reopen if needed.
