### ISSUE TITLE
phonopy-bandplot --gnuplot should not require --legacy

### ISSUE THREAD

**Issue by atztogo** [phonopy/phonopy#133]
Currently 
```
phonopy-bandplot --gnuplot band.yaml
```
doesn't work properly, but the following works
```
phonopy-bandplot --gnuplot band.yaml --legacy
```

It is expected to work in the former way.

**Comment by kgmat** [comment]
Dear Dr. Togo, 

  I just created a PR for this issue.
  https://github.com/phonopy/phonopy/pull/134

Thanks

**Comment by atztogo** [comment]
Done by PR #134. Thanks.
