### ISSUE TITLE
Recentering in 'phonopy --symmetry', and aperiodic systems

### ISSUE THREAD

**Issue by ExpHP** [phonopy/phonopy#135]
In some circumstances, phonopy applies some form of "recentering" before writing PPOSCAR.  Because phonopy also always reduces coordinates into the unit cell, this translation can present challenges for code working with aperiodic systems:

**POSCAR**
```
generated by phonopy
1.0
8.799999999999999 0.000000000000000 0.000000000000000
0.000000000000000 8.799999999999999 0.000000000000000
0.000000000000000 0.000000000000000 8.799999999999999
C H
1 4
direct
0.390000000000000 0.390000000000000 0.390000000000000 C
0.461705558018936 0.461705558018936 0.461705558018936 H
0.318294441981064 0.318294441981064 0.461705558018936 H
0.461705558018936 0.318294441981064 0.318294441981064 H
0.318294441981064 0.461705558018936 0.318294441981064 H
```

**PPOSCAR**
```
generated by phonopy
   1.0
     8.7999999999999989    0.0000000000000000    0.0000000000000000
     0.0000000000000000    8.7999999999999989    0.0000000000000000
     0.0000000000000000    0.0000000000000000    8.7999999999999989
C H
   1    4
Direct
  0.0000000000000000  0.0000000000000000  0.0000000000000000
  0.0717055580189361  0.0717055580189361  0.0717055580189361
  0.9282944419810639  0.9282944419810639  0.0717055580189361
  0.0717055580189361  0.9282944419810639  0.9282944419810639
  0.9282944419810639  0.0717055580189361  0.9282944419810639
```

In the PPOSCAR above, you can see that the atoms are no longer chosen from a single image of the molecule, which presents a challenge if somebody wants to read this file and e.g. create an ASE `Atoms` with `pbc=False`.  But, to my understanding, this translation is not necessary for the structure to be symmetrized, because each spacegroup operation `(R, t)` on the translated structure admits a spacegroup operation on the original structure by similarity transform.  (Basically, if the recentering is done by adding a vector `c` then you compose the operations `(1, -c), (R, t), (1, +c)`)

So, could it be possible to add an option for `phonopy --symmetry` to not recenter PPOSCAR?  (by adjusting the printed spacegroup operators instead of the positions)

Alternatively, could the output of `phonopy --symmetry` possibly include the translation vector used for recentering, so that the user can easily undo the translation if desired?

**Comment by atztogo** [comment]
To undo, not only the shift, but also rotation has to be given. But it's quite easily to include and I agree it should be done. I also think that users who can understand this detail can use spglib without any difficulty, and it is my recommendation.

There are a few options for creating the primitive cell in spglib, https://spglib.github.io/spglib/api.html#spg-standardize-cell. PPOSCAR is currently made with `no_idealize=0`, which can contain a rotation (https://spglib.github.io/spglib/definition.html#rotation-introduced-by-idealization), too. If we want to avoid those, we can use `no_idealize=1`. With this, basis vectors can not be fully standardised. The other possibility is to apply the full standardinzation and using transformation matrix and origin shift, we can return the cell approximately back to the orientation of the input one. The difficulty is that how can tell this to users.

**Comment by ExpHP** [comment]
Ah, thanks, I was unaware about the rotation.

> I also think that users who can understand this detail can use spglib without any difficulty, and it is my recommendation.

Indeed, it looks like we can use spglib for our purposes.  I will note, the thing we are most interested in is actually not the symmetrized positions, but rather, the rotations & translations of the spacegroup operators that will be used by phonopy when it generates displacements.[^1]  To my understanding, phonopy does not apply these transformations to the structure when producing SPOSCAR, which is why it would be nice to have a way to obtain these spacegroup operators without these transformations.

For now though I will work on something that recovers the operations from spglib.

---
[^1]: We're trying to use a technique similar to phonopy to use symmetry to compute the derivative of some function with respect to atomic positions.  For this, we need the minimum displacements from phonopy as well as the spacegroup operators that can be used on these displacements to generate the rest of the data.

**Comment by atztogo** [comment]
I see. Then probably the following might be more convenient for your,
```
import phonopy
ph = phonopy.load("phonopy_disp.yaml", produce_fc=False)
symmetry = ph.symmetry
```
(please have a look at phonopy.load docstring for more options.)
By this, you can get `Symmetry` instance of the supercell.
https://github.com/phonopy/phonopy/blob/develop/phonopy/structure/symmetry.py
Or rather, `ph.symmetry.dataset` will give you the spglib symmetry dataset, by which you see more symmetry details.
Note that, in phonopy, no symmetry search is performed for the input crystal structure, but only done for the supercell and the primitive cell (`ph.primitive_symmetry`).

**Comment by ExpHP** [comment]
Thanks!  `Phonopy.symmetry` does look like a reasonable solution, with usefully-defined `rotations` and `translations`.  And it makes sense that this should give data for the supercell, so this is no problem.  (I've just been working on 1x1x1 supercells lately so I didn't think of it)

Since this solves my use case I will close this for now.
