### ISSUE TITLE
Issue in running Phonopy

### ISSUE THREAD

**Issue by manish9909** [phonopy/phonopy#139]
Hi Admin,

I had been trying to run phonopy in our university HPC, the installation was smooth, and had no problem with that. But when I am running it, It has been showing the same problem constantly, which I am unable to understand. 

TypeError: get_stabilized_reciprocal_mesh() got an unexpected keyword argument 'is_dense'

I also attached the full error text file below:

[error.txt](https://github.com/phonopy/phonopy/files/5929494/error.txt)

Thanks in advance,

Best,
Manish

**Comment by atztogo** [comment]
Please install the latest phonopy and spglib.

**Comment by manish9909** [comment]
Thanks, It worked.
