### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by prnvrvs** [phonopy/phonopy#144]
In phonopy/phonopy/qha/core.py , 
line number 539 should interchange with 542
These are coefficient of polynomial fitting of (Cv vs V) and (S vs V)

def write_heat_capacity_P_polyfit(self,
                                      filename='Cp-temperature_polyfit.dat',
                                      filename_ev='entropy-volume.dat',
                                      filename_cvv='Cv-volume.dat',
                                      filename_dsdvt='dsdv-temperature.dat'):
        wve = open(filename_ev, 'w')
        wvcv = open(filename_cvv, 'w')
        for i in range(1, self._len):
            t = self._temperatures[i]
            wve.write("# temperature %20.15f\n" % t)
            wve.write("# %20.15f %20.15f %20.15f %20.15f %20.15f\n" %
                      tuple(self._volume_cv_parameters[i - 1])) # line 539
            wvcv.write("# temperature %20.15f\n" % t)
            wvcv.write("# %20.15f %20.15f %20.15f %20.15f %20.15f\n" % 
                       tuple(self._volume_entropy_parameters[i - 1])) #line 541
            for ve, vcv in zip(self._volume_entropy[i - 1],
                               self._volume_cv[i - 1]):
                wve.write("%20.15f %20.15f\n" % tuple(ve))
                wvcv.write("%20.15f %20.15f\n" % tuple(vcv))
            wve.write("\n\n")
            wvcv.write("\n\n")
        wve.close()
        wvcv.close()

**Comment by atztogo** [comment]
Which lines in the current develop?
https://github.com/phonopy/phonopy/blob/1d7dc53d3801d693fed5b7c7ede6cc1d1369ec48/phonopy/qha/core.py#L494-L528

**Comment by prnvrvs** [comment]
Need to swap (507-508)  with (504-505)
wve.write associate with entropy-volume.dat while wvcv.write associate with Cv-volume.dat, hence 
correct syntax will be
line(504-505)
wve.write("# %20.15f %20.15f %20.15f %20.15f %20.15f\n" % 
                   tuple(self._volume_entropy_parameters[i - 1])) 

line(507-508)
wvcv.write("# %20.15f %20.15f %20.15f %20.15f %20.15f\n" % 
                    tuple(self._volume_cv_parameters[i - 1]))

**Comment by atztogo** [comment]
I'm sorry for my late reply. I will fix it. Thanks!

**Comment by atztogo** [comment]
Thanks. This was fixed on the develop branch.

**Comment by atztogo** [comment]
I close  this issue because it was fixed.
