### ISSUE TITLE
Consistency of the crystal structure used to compute shortest vectors in get_smallest_vectors() and that for the force_constant

### ISSUE THREAD

**Issue by algorithmx** [phonopy/phonopy#147]
https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/harmonic/dynamical_matrix.py#L275

Dear Prof. Atsushi Togo,

(the mail-server of phonopy-users@lists.sourceforge.net does not respond when I send the email to ask for help. Since the question is related to the details of the code, I think probably I can ask here ...)

I am trying to understand the source code of Phonopy and got confused when I am looking at functions
`get_smallest_vectors()`  in  structure/cells.py 
and 
`_run_py_dynamical_matrix(self, q)`  in  harmonic/dynamical_matrix.py

Since the function `_run_py_dynamical_matrix()` uses both the "shortest vectors"
`vecs = self._smallest_vectors`
and the "force constant" 
`fc = self._force_constants`
they have to be consistent. I have tracked the calculation of them and found that `self._force_constants` is actually calculated in 

api_phonopy.py line 2977 `get_phonopy_fc2` => force_constants.py line 58 `get_fc2` => line 226 `distribute_force_constants` => `phonoc.distribute_fc2`

whereas `self._smallest_vectors` is calculated in 

dynamical_matrix.py line 140 => cells.py line 712 => line 727 => `phonoc.gsv_set_smallest_vectors()`

However, during the first calculation, the variables "unitcell" and "supercell" are passed without modification to reach the function `phonoc.distribute_fc2`, but in the function `get_smallest_vectors()`, the atom positions are further modified with respect to the Niggli reduced bases. Only after this modification, the final worker `phonoc.gsv_set_smallest_vectors()` is called. So I think the shortest vectors are calculated from a MODIFIED (but must be equivalent) structure, which is different from what it seems to be. 

These details should not affect the final result of dynamical matrix because atoms are kept in order during the entire calculation. But since the force constants are calculated externally via, for example, VASP, how can I understand the consistency of the crystal structure used by VASP and the crystal structure used by `phonoc.gsv_set_smallest_vectors()` ? Have I missed some important works done by Phonopy ? 

Best regards,
Yunlong LIAN

**Comment by atztogo** [comment]
There may be two issues. I will comment one by one.

1. `_run_py_dynamical_matrix(self, q)`

    This exists only for the testing purpose and not used in the normal phonopy calculation. This works only for full size force constants (https://phonopy.github.io/phonopy/setting-tags.html#full-force-constants.)

2. Coordinates

    The coordinates of points of atoms are transformed back in C code, here,
    https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/c/phonopy.c#L613-L616
    Yes, so the coordinates have to be consistent.

**Comment by algorithmx** [comment]
Thanks for the quick response! Replies are inlined.

> There may be two issues. I will comment one by one.
> 
> 1. `_run_py_dynamical_matrix(self, q)`
>    This exists only for the testing purpose and not used in the normal phonopy calculation. This works only for full size force constants (https://phonopy.github.io/phonopy/setting-tags.html#full-force-constants.)

I think the actual worker to set up the dynamical matrix should be `_run_c_dynamical_matrix`,
starts from here 
https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/harmonic/dynamical_matrix.py#L220

> 2. Coordinates
>    The coordinates of points of atoms are transformed back in C code, here,
>    https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/c/phonopy.c#L613-L616
>    
>    Yes, so the coordinates have to be consistent.

The argument sent to `phonoc.gsv_set_smallest_vectors` is `trans_mat_inv.T` but appeared in the above piece of code as `trans_mat` ... That confused me :-D But I got new question now: could you please explain the purpose of the few lines below this line ? Especially the use of `np.rint` ? I know it is very subtle perhaps we need examples (I'll provide one later)
https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/structure/cells.py#L937
I feel very uncomfortable with `np.rint` since
`np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])` 
gives
`array([-2., -2., -0.,  0.,  2.,  2.,  2.])`
according to the reference https://numpy.org/doc/stable/reference/generated/numpy.rint.html .
In fact I am developing a code and now I am writing an interface to Phonopy. During the development it seems to me that I have met the same problem. Instead I choose some function which returns the largest integer below the given float, not `np.rint`.

**Comment by atztogo** [comment]
To bring the point inside an interval of [-0.5, 0.5]. I don't want to answer your detailed questions. I am not your supervisor. Please think a little bit more before writing comments.

**Comment by algorithmx** [comment]
> To bring the point inside an interval of [-0.5, 0.5]. I don't want to answer your detailed questions. I am not your supervisor. Please think a little bit more before writing comments.

Thanks Prof. Togo. Now I fully understand the code. The lines containing `np.rint` does not change the relative positions of the atoms, because they are simply translations by Bravais lattice vectors. I can safely conclude that the transformations in function `_run_sparse()`, via `_transform_cell_basis()`, does not change the relative positions of the atoms. The "smallest vectors" are thus calculated with respect to the original crystal structure, in a more convenient basis.
