### ISSUE TITLE
Potential repetition in calculating `lattice_points` in function `_transform_cell_basis()`

### ISSUE THREAD

**Issue by algorithmx** [phonopy/phonopy#148]
https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/structure/cells.py#L945

There is no problem in the code here, but just a suggestion: from this line until line 
https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/structure/cells.py#L967
I think every call to `_transform_cell_basis` gives the same definite result for `lattice_points`. It is then probably better to replace these lines by a constant array, which is just the result, to avoid repeated calculations.

**Comment by algorithmx** [comment]
I don't know where would be the best place to set up this constant, so I choose not to touch the code ...

**Comment by atztogo** [comment]
I can't understand what you mean.

**Comment by algorithmx** [comment]
> https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/structure/cells.py#L945
> 
> There is no problem in the code here, but just a suggestion: from this line until line
> https://github.com/phonopy/phonopy/blob/75b17493b1d7b841a710b8e75d05304c79dc5787/phonopy/structure/cells.py#L967
> 
> 
> I think every call to `_transform_cell_basis` gives the same definite result for `lattice_points`. It is then probably better to replace these lines by a constant array, which is just the result, to avoid repeated calculations.

I mean line 945 to line 967 can be computed explicitly, giving (numpy version >1.13)
```
array([[-2, -2, -2],
       [-2, -2, -1],
       [-2, -2,  0],
       [-2, -1, -2],
       [-2, -1, -1],
       [-2, -1,  0],
       [-2,  0, -2],
       [-2,  0, -1],
       [-2,  0,  0],
       [-1, -2, -2],
       [-1, -2, -1],
       [-1, -2,  0],
       [-1, -1, -2],
       [-1, -1, -1],
       [-1, -1,  0],
       [-1, -1,  1],
       [-1,  0, -2],
       [-1,  0, -1],
       [-1,  0,  0],
       [-1,  0,  1],
       [-1,  1, -1],
       [-1,  1,  0],
       [-1,  1,  1],
       [ 0, -2, -2],
       [ 0, -2, -1],
       [ 0, -2,  0],
       [ 0, -1, -2],
       [ 0, -1, -1],
       [ 0, -1,  0],
       [ 0, -1,  1],
       [ 0,  0, -2],
       [ 0,  0, -1],
       [ 0,  0,  0],
       [ 0,  0,  1],
       [ 0,  0,  2],
       [ 0,  1, -1],
       [ 0,  1,  0],
       [ 0,  1,  1],
       [ 0,  1,  2],
       [ 0,  2,  0],
       [ 0,  2,  1],
       [ 0,  2,  2],
       [ 1, -1, -1],
       [ 1, -1,  0],
       [ 1, -1,  1],
       [ 1,  0, -1],
       [ 1,  0,  0],
       [ 1,  0,  1],
       [ 1,  0,  2],
       [ 1,  1, -1],
       [ 1,  1,  0],
       [ 1,  1,  1],
       [ 1,  1,  2],
       [ 1,  2,  0],
       [ 1,  2,  1],
       [ 1,  2,  2],
       [ 2,  0,  0],
       [ 2,  0,  1],
       [ 2,  0,  2],
       [ 2,  1,  0],
       [ 2,  1,  1],
       [ 2,  1,  2],
       [ 2,  2,  0],
       [ 2,  2,  1],
       [ 2,  2,  2]])
```
It is the same for every calculation. So instead of returning `lattice_points` from `_transform_cell_basis()`, one can write the above result into the code (by defining a global constant somewhere in the code) and directly quote it when necessary. This saves time :-)
