### ISSUE TITLE
set _run_dense = True, phonopy will report error

### ISSUE THREAD

**Issue by Simon-lxq** [phonopy/phonopy#152]
Dear Pro Atsushi Togo:
there are some problems in the new function '_run_dense'. if i try set store_dense_vectors=True. the phonopy will report the error (Segmentation fault (core dumped)). And i don't know why this problem happens.
And this kind of problem will occur when there are too many atoms. If there is 10000 atoms in a unit cell, the smallest_vectors will be (10000,10000,27,3), the sparse array is too big to calculate. which might be the reason of 'Segmentation fault'.
by the way, this problem really troubled me for a long time, I sincerely look forward to your reply.

liuxq

**Comment by atztogo** [comment]
Because it is under the development.
