### ISSUE TITLE
what is the absolute unit in FORCE_SETS of phonopy ?

### ISSUE THREAD

**Issue by algorithmx** [phonopy/phonopy#156]
https://github.com/phonopy/phonopy/blob/6e9a5c2c180ed07e7927478b4500c4876734f9c2/phonopy/file_IO.py#L114

Simple question : What is the absolute unit of numbers loaded by this function `parse_FORCE_SETS()` ? Are there any settings to change this?

**Comment by atztogo** [comment]
Do you mean about the values in `FORCE_SETS` file?

**Comment by algorithmx** [comment]
there is no information on the absolute unit neither in 
https://github.com/phonopy/phonopy/blob/960855ad43b53a093d942af1afa22685907002b5/phonopy/api_phonopy.py#L926
nor 
https://github.com/phonopy/phonopy/blob/34df0c925e4642fd8b6d7f8c562ebdc1ae91080b/phonopy/harmonic/force_constants.py#L73

**Comment by algorithmx** [comment]
> Do you mean about the values in `FORCE_SETS` file?

Yes, and more precisely, the numbers after loading `FORCE_SETS` via

`force_sets = phonopy.file_IO.parse_FORCE_SETS(filename=force_filename)`

and after calling 

`phonon.set_displacement_dataset(force_sets)`
`phonon.produce_force_constants()`

Sorry professor, the internet connection to github is very unstable here and I cannot reply your comments in time ...

**Comment by atztogo** [comment]
It's arbitrary. For calculator interfaces, for example, https://phonopy.github.io/phonopy/interfaces.html#physical-unit-system-for-calculator.
