### ISSUE TITLE
Band labels rendering does not work without LaTeX

### ISSUE THREAD

**Issue by mystery-e204** [phonopy/phonopy#160]
Hi,

It seems that plotting with the `band_labels` setting enabled, phonopy tries to render the text using LaTeX. Unfortunately, if LaTeX is not installed on the machine, there is no fallback and the code crashes. Matplotlib offers [builtin math rendering](https://matplotlib.org/stable/tutorials/text/mathtext.html) that does not rely on an external LaTeX engine to be present. Would it be possible to have this as a fallback or even default?

**Comment by atztogo** [comment]
I am going to work for it.
