### ISSUE TITLE
Wrong unit conversion in VASP 6.x

### ISSUE THREAD

**Issue by NewSigma** [phonopy/phonopy#168]
This issue relates to #155

At  least in VASP 6.1.0, there is no need to carry out additional unit conversion. The code of VASP 6.1.0 says

```
CALL XML_TAG("dynmat")
CALL XML_VECARRAY("hessian")
CALL XML_ARRAY_REAL(EIGENVECTORS)
CALL XML_CLOSE_TAG
```

and there is no unit conversion as #155 says. I believe the change took place in a minor version later than VASP 6.1.0 but I'm not sure which one.

I run example/NaCl-VASPdfpt using VASP 6.1.0 + phonopy 2.12.0 and got the following frequencies

```
# End points of segments: 
#   0.00000000 0.15219320 0.30438650 0.48012410 0.63231730 
0.000000 -0.001150
0.003044 0.005056
0.006088 0.010302
0.009132 0.015494
0.012176 0.020663
0.015219 0.025809
0.018263 0.030932
0.021307 0.036028
0.024351 0.041093
0.027395 0.046125
0.030439 0.051121
0.033482 0.056077
0.036526 0.060992
0.039570 0.065863
...
```

Using the provided FORCE_CONSTANTS, I got

```
# End points of segments: 
#   0.00000000 0.15219320 0.30438650 0.48012410 0.63231730 
0.000000 -0.028264
0.003044 0.074549
0.006088 0.156897
0.009132 0.237380
0.012176 0.317343
0.015219 0.397016
0.018263 0.476453
0.021307 0.555664
0.024351 0.634638
0.027395 0.713359
0.030439 0.791808
0.033482 0.869962
0.036526 0.947801
0.039570 1.025301
...
```
The frequencies calculated using VASP 6.1.0 are smaller by a factor of 15.633302.

**Comment by atztogo** [comment]
Thanks for your report @NewSigma.
Right now, it seems the following versions are available: v6.1.0, v6.1.1, v6.1.2, v6.2.0, v6.2.1. I will check them.

**Comment by atztogo** [comment]
Comparing the five versions of VASP, phonopy seems to need unit change from v6.2.0. My fix is found at https://github.com/phonopy/phonopy/pull/169.

**Comment by NewSigma** [comment]
Thank you for your quick fixing!
