### ISSUE TITLE
One warning occurs when using phonopy-vasp-efe: 'Warning: Probably xml structure of vasprun.xml_1.001 is broken.', is there some trouble in vasprun.xml?

### ISSUE THREAD

**Issue by Tago1** [phonopy/phonopy#188]

**Comment by atztogo** [comment]
Could you send your question to the phonopy mailing list?

**Comment by atztogo** [comment]
I close this issue for this question is considered better to discuss on the phonopy mailing list. If you will need to discuss here, please reopen this issue.
