### ISSUE TITLE
Handling of compressed files

### ISSUE THREAD

**Issue by JaGeo** [phonopy/phonopy#198]
Dear Togo, 

I am working a lot with both VASP, pymatgen and phonopy. Very often, I am gzipping my files (simplify data transfer/safe storage etc). Pymatgen can work with gzipped files directly by using monty https://guide.materialsvirtuallab.org/monty/ and zopen instead of open.

Would there be interest to add such a support for phonopy as well?

Thank you very much.

Best
JG

**Comment by atztogo** [comment]
I don't see exactly what you expect. But I think compression is a good idea. HDF5 files support compression.

In my usage, I usually dump phonopy data (e.g. displacements, forces, NAC params) into `phonopy_params.yaml`-like-file using API, `Phonopy.save()`, or command line options, and then use xz command to compress it. Phonopy supports .gz and .xz in reading the yaml file:

https://github.com/phonopy/phonopy/blob/063e48505b866468bbd84eedd914cf7b1b34ac32/phonopy/interface/phonopy_yaml.py#L643-L669

References to API and command options:
https://phonopy.github.io/phonopy/phonopy-module.html#shortcut-to-load-input-files-phonopy-load
https://phonopy.github.io/phonopy/phonopy-load.html
https://phonopy.github.io/phonopy/setting-tags.html#summary

**Comment by JaGeo** [comment]
Thank you for the answers! 

I would like to have the option to start the creation of the force constants or BORN file from compressed vasprun.xml's.

**Comment by atztogo** [comment]
Do you mean each vasprun.xml file is compressed?

**Comment by atztogo** [comment]
How about having the following function?
https://github.com/phonopy/phonopy/blob/f354d82f3673999dc93855bd07add0f2ebf23ac9/phonopy/file_IO.py#L927-L949

**Comment by JaGeo** [comment]
Thank you for the suggestion. I'm not yet sure how this would be used in the most efficient way. Isn't it simpler to replace "open" with a function or method that can also handle compressed files?

**Comment by atztogo** [comment]
> I'm not yet sure how this would be used in the most efficient way.

What is the most efficient way?

I can not see your use-case. I understand you have it in your mind, but your scope may be limited to your use case but I probably have to support people in wider scope. You can explain more details, otherwise no chance for me to understand what we should do.

**Comment by JaGeo** [comment]
I understand. Would it be okay if I simply draft a pull-request at some point to indicate and explain my thoughts better? And, then you could decide whether you like it or not?

**Comment by atztogo** [comment]
My question is probably not very much about the code, but the user-case. If I know the use case, I may be able to solve it directly or indirectly.

So if your use-case is, for example,
```
% phonopy -f vasprun-1.xml.xz  vasprun-2.xm.xz  vasprun-3.xml.xz ..
```
Then the code may be written as

```python
myio = get_module_to_decompress(filename)
with myio.open(filename) as f:
    ...
```

If this is the requirement, a build-in simple solution is better than relying on an external library. Dependency is not as controllable as build-in code (https://abseil.io/resources/swe-book/html/ch21.html).

**Comment by atztogo** [comment]
https://github.com/phonopy/phonopy/pull/199.

**Comment by atztogo** [comment]
@JaGeo, please let me know if it works. Testing user-interface is uneasy. Do you think I should write documentation for this?

**Comment by JaGeo** [comment]
- The forces can be collected when the vasprun.xml's are gzipped (`phonopy -f ....` ) via the command-line when all yaml files are unzipped. (Or is there a way to work with a gzipped yaml-file?)
- Creation of born file is also working when I use `phonpy-vasp-born vasprun.xml-gz`. 
- What does not seem to work is: `phonopy-vasp-born  --outcar OUTCAR.gz POSCAR.gz`.

It might be good to document it.

**Comment by atztogo** [comment]
Thanks for your test.

> Or is there a way to work with a gzipped yaml-file? I guess only via the API.

You are good at finding it. This is a little bit more tricky to handle. Phonopy-commands (`phonopy` and `phonopy-load`) are out of API and are standing on very fragile code base to support various complicated options.

I push an update to develop branch with fingers crossed.
https://github.com/phonopy/phonopy/commit/014b6538a904009e1d6195d83b0f403359abdc99

**Comment by JaGeo** [comment]
This has worked out. I can work with the compressed yamls now.

Only thing left that does not seem to work is reading a compressed POSCAR.gz.

**Comment by atztogo** [comment]
Why do you compress POSCAR? It will not be so large.

**Comment by JaGeo** [comment]
True. It's fine like this from my side. Thank you in any case!
