### ISSUE TITLE
Questions about the 'unfolding' method

### ISSUE THREAD

**Issue by yliu1240** [phonopy/phonopy#208]
To whom this may concern,
Hi! I'm wondering if there's an example or script about the unfolding method which can treat vacancies in the structure.

Thanks a lot and have a nice day!

Best regards,

**Comment by yliu1240** [comment]
Sorry, I think I find the example from tests.

Thank you very much.

Best regards,

> To whom this may concern, Hi! I'm wondering if there's an example or script about the unfolding method which can treat vacancies in the structure.
> 
> Thanks a lot and have a nice day!
> 
> Best regards,

**Comment by yliu1240** [comment]
Hi!
Though overall it's working, I'm struggling to generate q-points myself. I'm wondering if there's an easier way, or something to refer to, to generate q-points from given band paths.

Thanks again and have a nice day!

Best regards,

**Comment by atztogo** [comment]
No documentation means no support publicly.

**Comment by yliu1240** [comment]
Hi!
OK! Thank you anyway!

Have a nice weekend!

Best regards,
