### ISSUE TITLE
How to calculate the PDOS of a cluster

### ISSUE THREAD

**Issue by Simon-lxq** [phonopy/phonopy#209]
Dear Sir, 

I am trying to calculate the PDOS of Benzene cluster structure, no periodic boundary condition, just like the example in [Phonopy-Spectroscopy](https://github.com/JMSkelton/Phonopy-Spectroscopy/tree/master/Examples/Benzene-Derivatives/Benzene). I know this question is boring, but in common process, I type the command like "phonopy -p -s mesh.conf". The PDOS contains nothing. So I want to know how to calculate the phonon DOS of a cluster structure, what should I do?

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
