### ISSUE TITLE
 extracting FORCE_CONSTANTS from the FORCE_SETS.

### ISSUE THREAD

**Issue by chejunwei2** [phonopy/phonopy#216]
Dear atztogo,
I first calculated the FORCE_SETS using the finite difference method, and then I wrote the FORCE_CONSTANTS from the FORCE_SETS. However, I found that the matrix size of FORCE_CONSTANTS calculated by the DFPT method is different from the format converted from the FORCE_SETS, although the two are equivalent in lattice dynamics. My primitive cell contains 5 atoms, and the calculated FORCE_CONSTANTS for supercell (3x3x1)  are as follows:
1) calculated from DFPT:

   **45   45
    1 1
    18.702488206629997    -0.000000000000000     0.000000000000000
    -0.000000000000000    18.702489647949999    -0.000000000000000
     0.000000000000000    -0.000000000000000    13.630046166449999
    1 2
     ..........**

2) wrote from FORCE_SETS:
   **5   45
1 1
    18.702488206629997    -0.000000000000000     0.000000000000000
    -0.000000000000000    18.702489647949999    -0.000000000000000
     0.000000000000000    -0.000000000000000    13.630046166449999**1
**1 2
............**

I want to calculate the FORCE_CONSTANTS for ShengBTE to get thermal conductivity, but the ShengBTE can only recognize the format calculated by the DFPT method. So, when  extracting FORCE_CONSTANTS form FORCE_SETS, what should I do to get the same matrix size as DFTP? Thanks very much.

Best regards,
Junwei

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list. I close this issue, but please reopen whenever needed.
