### ISSUE TITLE
2.16.1: Broken when BUILD_SHARED_LIBRARIES=ON

### ISSUE THREAD

**Issue by yurivict** [phonopy/phonopy#234]
With ```PHONOPY=ON``` and ```BUILD_SHARED_LIBRARIES=ON``` the build breaks:
```
CMake Error at CMakeLists.txt:42 (add_library):
  No SOURCES given to target: phpy
```

clang-14
FreeBSD 13,1 STABLE

**Comment by atztogo** [comment]
@yurivict, thanks for notifying it. I fixed it: https://github.com/phonopy/phonopy/commit/b2e7b1d6f7280b2d4d99fb74737b2bffbc86fd08.

**Comment by yurivict** [comment]
This works, thanks!
