### ISSUE TITLE
NAC not working with vasprun.xml

### ISSUE THREAD

**Issue by mystery-e204** [phonopy/phonopy#263]
Hi,

I tried running phonopy to plot the phonon dispersion of a finished VASP run but when I try setting `NAC = .TRUE.` it does not work. I followed the [VASP-DFPT tutorial](https://phonopy.github.io/phonopy/vasp-dfpt.html) but I used finite differences instead of perturbation theory.

Here is what I did:
1) Run VASP in a supercell (4x4x4) with `IBRION = 6` to generate the Hessian matrix in vasprun.xml.
2) Run `phonopy -fc vasprun.xml` to generate FORCE_CONSTANTS file.
3) Provide
   - POSCAR-unitcell
   - BORN
   - band.conf
4) Run `phonopy -c POSCAR-unitcell --dim="4 4 4" --readfc -p band.conf`

This is in my band.conf:
```
BAND = ...
BAND_POINTS = 61
FC_SYMMETRY = .TRUE.
PRIMITIVE_AXES = AUTO
NAC = .TRUE.
```

This is the result:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/43782561/222258090-3b7e2b9e-8452-464e-ae30-193d28e3de60.png">
There is no LO-TO splitting due to NAC. I might be doing something wrong but I never got any errors and the output says:
```
Force constants are read from "FORCE_CONSTANTS".
...
NAC parameters were read from "BORN".
```

**Comment by atztogo** [comment]
Using [this example](https://github.com/phonopy/phonopy/tree/develop/example/NaCl) and `band.conf`:
```
DIM = 2 2 2
PRIMITIVE_AXIS = AUTO
BAND = 0.0 0.0 0.0  0.5 0.0 0.0  0.5 0.5 0.0  0.0 0.0 0.0  0.5 0.5 0.5
BAND_POINTS = 61
FC_SYMMETRY = .TRUE.
NAC = .TRUE.
```

I ran phonopy (develop branch 5d9f37e9, and also latest conda package macOS ARM64)
```
% phonopy -c POSCAR-unitcell band.conf -p
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                      2.17.1

Compiled with OpenMP support (max 10 threads).
Python version 3.10.8
Spglib version 2.0.2

"band.conf" was read as phonopy configuration file.
Crystal structure was read from "POSCAR-unitcell".
Unit of length: angstrom
Band structure mode
Settings:
  Non-analytical term correction (NAC): on
  Force constants symmetrization: on
  Supercell: [2 2 2]
  Primitive matrix (Auto):
    [0.  0.5 0.5]
    [0.5 0.  0.5]
    [0.5 0.5 0. ]
Spacegroup: Fm-3m (225)
Use -v option to watch primitive cell, unit cell, and supercell structures.

Forces and displacements were read from "FORCE_SETS".
Computing force constants...
Max drift of force constants: 0.040159 (xx) 0.000009 (xx)
Max drift after symmetrization by translation: 0.000000 (zz) 0.000000 (zz)

NAC parameters were read from "BORN".
Use NAC by Gonze et al. (no real space sum in current implementation)
  PRB 50, 13035(R) (1994), PRB 55, 10355 (1997)
  G-cutoff distance: 1.16, Number of G-points: 307, Lambda: 0.19

Reciprocal space paths in reduced coordinates:
[ 0.000  0.000  0.000] --> [ 0.500  0.000  0.000]
[ 0.500  0.000  0.000] --> [ 0.500  0.500  0.000]
[ 0.500  0.500  0.000] --> [ 0.000  0.000  0.000]
[ 0.000  0.000  0.000] --> [ 0.500  0.500  0.500]
```

then I got the following plot.

![Figure_1](https://user-images.githubusercontent.com/953404/222307758-2bc54459-fec3-4fb4-96cc-9732a220a390.png)

Could you try the same?
If it works, could you show your `BORN` file?

**Comment by mystery-e204** [comment]
Sure! I downloaded the example and reran your exact steps. I also get the same output as you. So in this case it is working correctly.

Here is my BORN file (MgO):
```
# epsilon and Z* of atoms 1 2
   3.12794112    0.00000000    0.00000000   -0.00000000    3.12794112    0.00000000   -0.00000000    0.00000000    3.12794112
   1.96905530    0.00000000   -0.00000000    0.00000000    1.96905530   -0.00000000   -0.00000000    0.00000000    1.96905530
  -1.96905530   -0.00000000    0.00000000   -0.00000000   -1.96905530    0.00000000    0.00000000   -0.00000000   -1.96905530
```

**Comment by atztogo** [comment]
It seems your phonon frequency is very large and probably the values in BORN is negligible with respect to your force constants, i.e., physical unit mismatch, I guess.

**Comment by mystery-e204** [comment]
Ah, that makes sense. On closer inspection, I can see that the optical modes split with `NAC = .true.` but it's only very tiny. It seems there might be a unit mismatch when importing reading from vasprun.xml.

I think the problem is that the VASP version is not written consistently to the XML. I have an idea of how to fix that since newer VASP versions write an XML tag together with the Hessian that reports the unit (e.g. THz^2). However, we will first run a couple of tests to see which VASP versions work and which don't. That way, we can apply a fix that works in general, also for older versions.

I will update this thread when I know more and I can maybe make a PR.

Thanks, Togo :)

**Comment by mystery-e204** [comment]
I think we could even close this issue, because the problem is more related to units and parsing the XML from VASP.

**Comment by atztogo** [comment]
Current implementation about it is here,
https://github.com/phonopy/phonopy/blob/89421e455718174ed13f540973c9089072570137/phonopy/interface/vasp.py#L633-L636
