### ISSUE TITLE
inf gruneisen in phonopy

### ISSUE THREAD

**Issue by palashd1** [phonopy/phonopy#273]
Dear Users,

I am facing an issue while computing gruneisen in Phonopy (2.18).

```
phonopy/gruneisen/core.py:135: RuntimeWarning: divide by zero encountered in true_divide
  self._gruneisen = -edDe / self._delta_strain / self._eigenvalues / 2
```
I had created orig plus minus volumes and computed phonon dispersions accordingly  described in example folder for NaCl.
I had used 2x1x1 supercell.
Python version: 3.8.16
I would appreciate your assistance in this matter.

Thanks and regards,
Palash Swarnakar

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
