### ISSUE TITLE
Number of digits in thermal displacement matrices output

### ISSUE THREAD

**Issue by JaGeo** [phonopy/phonopy#275]
Dear Togo, 

I am working on some analysis of thermal displacement matrices again. I am wondering if we could extend the number of digits in the tdismat.cif and thermal_displacement_matrices.yaml files for the matrix elements after the point from 5 to maybe 7. Some of the matrix elements are very small and we otherwise mostly get Zeros for them. Postprocessing the data directly from the files would also be easier in this way.

**Comment by atztogo** [comment]
@JaGeo, for `thermal_displacement_matrices.yaml`, we can. For CIF, if it is allowed as the format, it is of course fine. Do you know it?

**Comment by JaGeo** [comment]
I haven't found any restriction with regard to the number of digits for the CIF but I am not completely sure. I am closing the issue for now. Thank you!
