### ISSUE TITLE
The interface of phonopy to lammps does't work

### ISSUE THREAD

**Issue by jinxin68** [phonopy/phonopy#287]
I try to run the example of lammps in ~/phonopy/example/Ti-lammps, but it failed. This problem seems to be caused by incorrect format of structure.
![image](https://github.com/phonopy/phonopy/assets/102202772/f4140219-a48e-4fe3-9c25-8a9c2c1a5a42)

**Comment by atztogo** [comment]
I am not very familiar with LAMMPS, but probably you need the latest versions of LAMMPS.

**Comment by jinxin68** [comment]
Thank you for your suggestion !
 I have updated  the version of lammps, but it still doesn't work. And I am unable to open the structure by visualization program,such as ovito.
![image](https://github.com/phonopy/phonopy/assets/102202772/80d502d7-4784-4ad3-aeb7-c7b06ca27e8d)

**Comment by jinxin68** [comment]
Thank you for your suggestion !
 I have updated  the version of lammps, but it still doesn't work. And I am unable to open the structure by visualization program,such as ovito.
![Uploading image.png…]()

**Comment by atztogo** [comment]
Atom Type Labels is New in version 15Sep2022 of LAMMPS. https://docs.lammps.org/Howto_type_labels.html

**Comment by jinxin68** [comment]
thank you！

**Comment by atztogo** [comment]
I will update the LAMMPS interface page to clarify the supported LAMMPS version. Thanks for your raising issue.
