### ISSUE TITLE
the MODULATION tag is only for VASP format by now, could you add the interface to other calculators? like ABACUS?

### ISSUE THREAD

**Issue by xdzhu** [phonopy/phonopy#299]
After using phonopy to generate different ABACUS structure files STRU-00*, and performing scf calculations respectively, I got FORCE_SETS using phonopy.
In this process, phonopy knows that the unit of length is **a.u.**. However, when I perform the "MODULATION = 1 1 1, 0 0 0 1 1" to generate the modulated ABACUS structure files, I found that phonopy treat the FORCE_SETS and qpoints.yaml as the type of VASP and then generate MPOSCAR-001 in **the unit of Angstrom** instead of recognizing the ABACUS calculator with length unit of **a.u.**. 
I found it is because the **modulation.py is only for VASP cases by now** (as figure below). Could you please add the support for other calculators? You can check the files in the compressed package below to reproduct my problem.

Best regards!

[modulation-issue.zip](https://github.com/phonopy/phonopy/files/12035166/modulation-issue.zip)

## generate modulation structure
phonopy -p modulation.conf --dim="4 4 2"

## generate eigenvector at 0 0 0
phonopy -p eigen.conf --dim="4 4 2"
 
![image](https://github.com/phonopy/phonopy/assets/55775434/aa7b5ffd-892a-48ed-9652-74205c4296af)

![f7d14a71c9ec242bd22d52612617881](https://github.com/phonopy/phonopy/assets/55775434/a5df4242-a030-4b60-ac01-5cb8ce8c3de5)

**Comment by atztogo** [comment]
Modulation is a legacy feature and it seems difficult to support interface by interface. This is because some interface requires not only crystal structure but also additional information in the input file that contains crystal structure (e.g., QE), and the additional information is not always given to phonopy at the current phonopy, e.g., reading crystal structure from `phonopy_disp.yaml`. It is possible to write out in general structure format, i.e., phonopy yaml format for example.

**Comment by atztogo** [comment]
I can't make its command-user-interface, but I prepared API to do it. If you are interested in it, please try `modulation` branch.

The following is the script that works in NaCl-QE example. Note that you need to create `FORCE_SETS` by `% phonopy -f NaCl-001.out NaCl-002.out`) before running the script.
```python
import phonopy
from phonopy.interface.calculator import read_crystal_structure
cell, optional_info = read_crystal_structure("NaCl.in", interface_mode="qe")
ph = phonopy.load("phonopy_disp.yaml")
ph.run_modulations([1, 1, 1], [[[0, 0, 0], 1, 1, 0]])
ph.write_modulations(calculator="qe", optional_structure_info=optional_info)
```

**Comment by atztogo** [comment]
I merged `modulation` branch to `develop`. So the API approach will work for a while. By this, I close this issue. Please freely reopen if you need.
