### ISSUE TITLE
The space group types of graphene identified by phonopy and vesta are different.

### ISSUE THREAD

**Issue by hongyi-zhao** [phonopy/phonopy#302]
I use phonopy and vesta to recognize the space group of graphene as follows:

```python
(datasci) werner@X10DAi:~/Downloads/vaspkit.1.4.1.linux.x64/vaspkit.1.4.1/examples/elastic/graphene_2D$ cat POSCAR 
graphene                                
   2.45999999999999996     
     0.5017101267393932   -0.8689896166573675    0.0000000000000000
     0.5017101267393932    0.8689896166573675    0.0000000000000000
     0.0000000000000000    0.0000000000000000   12.3099161555221404
   C 
     2
Direct
  0.0000026218347600  0.9999973781652400  0.5000000000000000
  0.6666673781652435  0.3333326218347565  0.5000000000000000

  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
(datasci) werner@X10DAi:~/Downloads/vaspkit.1.4.1.linux.x64/vaspkit.1.4.1/examples/elastic/graphene_2D$ phonopy --symmetry --tolerance 1e-8 -c POSCAR 
phonopy_version: '2.20.0'
space_group_type: 'Cmmm'
space_group_number: 65
point_group_type: 'mmm'
space_group_operations:
- rotation: # 1
  - [ 1,  0 , 0]
  - [ 0,  1 , 0]
  - [ 0,  0 , 1]
  translation: [ 0.00000,  0.00000,  0.00000 ]
- rotation: # 2
  - [-1,  0 , 0]
  - [ 0, -1 , 0]
  - [ 0,  0 ,-1]
  translation: [ 0.66667,  0.33333,  0.00000 ]
- rotation: # 3
  - [-1,  0 , 0]
  - [ 0, -1 , 0]
  - [ 0,  0 , 1]
  translation: [ 0.66667,  0.33333,  0.00000 ]
- rotation: # 4
  - [ 1,  0 , 0]
  - [ 0,  1 , 0]
  - [ 0,  0 ,-1]
  translation: [ 0.00000,  0.00000,  0.00000 ]
- rotation: # 5
  - [ 0,  1 , 0]
  - [ 1,  0 , 0]
  - [ 0,  0 ,-1]
  translation: [ 0.66667,  0.33333,  0.00000 ]
- rotation: # 6
  - [ 0, -1 , 0]
  - [-1,  0 , 0]
  - [ 0,  0 , 1]
  translation: [ 0.00000,  0.00000,  0.00000 ]
- rotation: # 7
  - [ 0, -1 , 0]
  - [-1,  0 , 0]
  - [ 0,  0 ,-1]
  translation: [ 0.00000,  0.00000,  0.00000 ]
- rotation: # 8
  - [ 0,  1 , 0]
  - [ 1,  0 , 0]
  - [ 0,  0 , 1]
  translation: [ 0.66667,  0.33333,  0.00000 ]
atom_mapping:
  1: 1
  2: 1
site_symmetries:
- atom: 1
  Wyckoff: 'j'
  site_point_group: 'mm2'
  orientation:
  - [ 0,  1,  1]
  - [ 0, -1,  1]
  - [ 1,  0,  0]
  rotations:
  - # 1
    - [ 1,  0,  0]
    - [ 0,  1,  0]
    - [ 0,  0,  1]
  - # 2
    - [ 1,  0,  0]
    - [ 0,  1,  0]
    - [ 0,  0, -1]
  - # 3
    - [ 0, -1,  0]
    - [-1,  0,  0]
    - [ 0,  0,  1]
  - # 4
    - [ 0, -1,  0]
    - [-1,  0,  0]
    - [ 0,  0, -1]
# Symmetrized conventional unit cell is written into "BPOSCAR" and
# Symmetrized primitive is written into "PPOSCAR" and 
# "phonopy_symcells.yaml".
# These yaml files can be read in a python script as follows:
#
# from phonopy.interface.phonopy_yaml import read_cell_yaml
# unitcell = read_cell_yaml("phonopy_symcells.yaml", "unitcell")
# primitive_cell = read_cell_yaml("phonopy_symcells.yaml", "primitive")
```
The result of vesta is as follows:

![image](https://github.com/phonopy/phonopy/assets/11155854/ff6268aa-d059-4d0a-a474-0409ab76417c)

As you can see, they give different space groups. Any tips/comments/explanations on the above results will be helpful.

Regards,
Zhao

**Comment by atztogo** [comment]
If this is a question, probably it is better to be posted to the phonopy mailing list. Here on github, it is preferable to discuss about code and the development. But, I'm not sure if vesta has its own engine to search space group type in it. So it gives always P1 for `POSCAR` format.

**Comment by hongyi-zhao** [comment]
> If this is a question, probably it is better to be posted to the phonopy mailing list. Here on github, it is preferable to discuss about code and the development. 

Thank you for your hints.

> But, I'm not sure if vesta has its own engine to search space group type in it. So it gives always P1 for `POSCAR` format.

Even so, I still have another question: for 2d material, why shouldn't we identify it as one of [the 17 plane groups](https://www.cryst.ehu.es/cgi-bin/plane/programs/nph-plane_getgen?from=index)?

**Comment by atztogo** [comment]
I don't see your question well, but one of my answers is that `phonopy --symmetry` considers your input has a 3D structure that lives in 3D lattice, which is the constraint of the command.

**Comment by hongyi-zhao** [comment]
> I don't see your question well, 

I mean, graphene is indeed a two-dimensional material composed of a single layer of carbon atoms arranged in a hexagonal lattice structure. So, why shouldn't be described by one of the 17 plane groups?

> but one of my answers is that `phonopy --symmetry` considers your input has a 3D structure that lives in 3D lattice, which is the constraint of the command.

However, I have come across [the subsequent account](https://blog.sciencenet.cn/blog-1502061-1201748.html) that presents graphene as possessing a distinct space group, P6/mmm (No. 191), contrasting with the findings derived from the aforementioned phonopy analysis:

![image](https://github.com/phonopy/phonopy/assets/11155854/af3e31c1-52f8-496c-be4f-c38cd65c4f30)

**Comment by atztogo** [comment]
Please post your question to the phonopy mailing list. I will close this issue.
