### ISSUE TITLE
Calculation of mesh with symmetry and the Python interface

### ISSUE THREAD

**Issue by pierre-24** [phonopy/phonopy#308]
Hello,

I'm trying to use Phonopy as a starting point to get an infrared spectrum, and I noticed an issue.

The geometry I'm using is the one of SiO2, found [in the repository of `Phonopy-Spectroscopy`](https://github.com/skelton-group/Phonopy-Spectroscopy/blob/master/example/a-SiO2/POSCAR). I followed the instructions for [VASP-DFPT](https://phonopy.github.io/phonopy/vasp-dfpt.html#vasp-dfpt-interface), set up a calculation for a 1x1x1 supercell (I know it is not ideal, this is just to be quick) and I generated the corresponding `FORCE_CONSTANTS` file (see `vasprun.xml` in attached file).

Then, I want to compute phonon frequency with `phonopy --readfc --mesh="1 1 1"`. With or without `--fc-symmetry`, I (as expected) get different results (see `mesh_nosym.yaml` and `mesh.yaml` in attached file). In particular, without `--fc-symmetry`, the first non-negligible frequency is 3.02450054 THz, while it is 3.0245737279 THz  with it.

However, my goal is to write a script to automatize this process. Thus, I start from the following code ...

```python
import phonopy

phonon = phonopy.load(phonopy_yaml='phonopy_disp.yaml', force_constants_filename='FORCE_CONSTANTS')
phonon.run_mesh([1, 1, 1], is_mesh_symmetry=True)

print(phonon.get_mesh_dict()['frequencies'])
```

... and the frequencies I get are equivalent to the one obtained **without** `--fc-symmetry`, though I set `is_mesh_symmetry=True` (which is in fact the default). I would prefer to get the other ones, if possible :)

Is there an issue with my code, or did I miss a step in my Python?

Thanks in advance :)

Attached file: [phonopy_mesh.zip](https://github.com/phonopy/phonopy/files/13032789/phonopy_mesh.zip)

**Comment by atztogo** [comment]
Normally phonopy computes force constants from dataset of atomic displacements and forces, and at the same time imposes translational symmetry when you use `phonopy.load`. However, since you read force constants, it is not symmetrized automatically. In this case, you have to symmetrize it by yourself as follows..

```python
import phonopy

phonon = phonopy.load(
    phonopy_yaml="phonopy_disp.yaml", force_constants_filename="FORCE_CONSTANTS"
)
phonon.run_mesh([1, 1, 1])
print(phonon.get_mesh_dict()["frequencies"])

phonon.symmetrize_force_constants()

phonon.run_mesh([1, 1, 1])
print(phonon.get_mesh_dict()["frequencies"])
```

**Comment by pierre-24** [comment]
Oh, that is why. Thanks :)
