### ISSUE TITLE
Normalization by N in calculating thermal displacements

### ISSUE THREAD

**Issue by 16hchung** [phonopy/phonopy#312]
Hello,

I am trying to understand your implementation for estimating thermal displacements. According to the [documentation on thermal displacements](https://phonopy.github.io/phonopy/formulation.html#thermal-displacement), thermal displacements should be normalized by the number of atoms in the primitive cell. However, I don't see a division by N in [ThermalDisplacements.run(...)](https://github.com/phonopy/phonopy/blob/97d9e77218e4a2934e59ff32c3b5c0cf14bd8234/phonopy/phonon/thermal_displacement.py#L212) or ThermalMotion._get_Q2(...) in the same file. Where is this normalization done?

**Comment by atztogo** [comment]
I don't remember but probably

https://github.com/phonopy/phonopy/blob/97d9e77218e4a2934e59ff32c3b5c0cf14bd8234/phonopy/phonon/thermal_displacement.py#L242

**Comment by 16hchung** [comment]
It looks like count is the number of qpoints in the mesh, not the number of atoms in the primitive cell

https://github.com/phonopy/phonopy/blob/97d9e77218e4a2934e59ff32c3b5c0cf14bd8234/phonopy/phonon/thermal_displacement.py#L241

**Comment by atztogo** [comment]
As documentation says, N is the number of unit cells, which is equivalent to the number of q-points.

**Comment by 16hchung** [comment]
Ah okay I misinterpreted as the number of atoms! Thank you for your help :)
