### ISSUE TITLE
API for Python: Non converged phonon band structure w/ ASE calculators

### ISSUE THREAD

**Issue by stefanbringuier** [phonopy/phonopy#327]
I'm finding that when I use the ASE to generate structures and calculate the forces using  ASE calculator interface for classical interatomic potentials, and then move it to Phonopy via the python API the phonon calculations are not converged, unless I use unreasonably large distance values. I am for sure using the ground-state (i.e., minimized unit cell) and the ASE units are `eV`, `Angstrom`, `eV/Angstrom`. Here is the code and outputs:

```python
import ase
from phonopy import Phonopy
from phonopy.structure.atoms import PhonopyAtoms
...
calculator =  ase.calculators.emt.EMT() # units eV, eV/Angstrom

 # ase.Atoms object w/ min. to ground-state
structure =  ase_copper          

phnpy_struct = PhonopyAtoms(
    symbols=structure.get_chemical_symbols(),
    positions=structure.get_positions(),
    cell=structure.get_cell(),
    masses=structure.get_masses(),
    )

phonons = Phonopy(
    phnpy_struct,
    supercell_matrix=[[6, 0, 0],
                      [0, 6, 0],
                      [0, 0, 6]],
    )
phonons.generate_displacements(distance=0.01)
sets_of_forces = []
supercells = phonons.get_supercells_with_displacements()

for i,d in enumerate(supercells):
    # Convert back to ASE
    d_ase = Atoms(symbols=d.get_chemical_symbols(),
        positions=d.get_positions(),
        cell=d.get_cell(),
        )
    d_ase.set_calculator(calculator)
    forces = d_ase.get_forces()
    sets_of_forces.append(forces)
  
sets_of_forces = np.array(sets_of_forces)
phonons.forces = sets_of_forces
phonons.produce_force_constants()
```
This runs with no issues and then running:
```python
phonons.auto_band_structure(npoints=100,plot=True,write_yaml=True)
```

produces the following:
![image](https://github.com/phonopy/phonopy/assets/2709082/698d22c4-4e59-46d6-b2be-09a8d38fd8b7)

**Importantly** if I keep increasing  displacement, e.g.,`distance=0.5`, I get result:

![image](https://github.com/phonopy/phonopy/assets/2709082/28aa1b68-6e5b-45b0-ae37-276512c89d96)

and then final at `distance=0.9` a converged band structure:

![image](https://github.com/phonopy/phonopy/assets/2709082/6309c053-bd70-4fad-a298-295c319a72bb)

## Question
This seems unreasonable values to use for harmonic approx method? Is there something fundamentally incorrect with what I'm doing?

Also, using a larger supercell doesn't appear to shift down the displacement distance required for convergence.

### Example notebook

https://github.com/stefanbringuier/randomonium/blob/main/notebooks/ASE_Phonopy_Testing.ipynb

**Comment by atztogo** [comment]
This issue is probably a question about usage of phonopy. I expect those questions to be sent to the phonopy mailing list, because people not only me can reply questions. Here, I hope that github issues is more likely used for the code development. I don't answer about ASE. I recommend to try `produce_force_constants(fc_calculator='alm')`.

**Comment by JaGeo** [comment]
Just also to add, there are many working examples where phonopy and ase are used successfully together (e.g., see here for one of my example use cases with EMT calculator https://jageo.github.io/Advanced_Jobflow_Tutorial/tutorial.html#workflow-to-compute-phonons-vibrational-properties-of-crystals). Most likely, something is off with your structure conversion (cartesian vs. direct coordinates maybe?).

**Comment by stefanbringuier** [comment]
> This issue is probably a question about usage of phonopy. I expect those questions to be sent to the phonopy mailing list, because people not only me can reply questions. Here, I hope that github issues is more likely used for the code development. I don't answer about ASE. I recommend to try `produce_force_constants(fc_calculator='alm')`.

Agree, this is about use, so will email the mailing list (wasn't aware). Will also add `kwarg`. Thank you.

**Comment by stefanbringuier** [comment]
> Just also to add, there are many working examples where phonopy and ase are used successfully together (e.g., see here for one of my example use cases with EMT calculator https://jageo.github.io/Advanced_Jobflow_Tutorial/tutorial.html#workflow-to-compute-phonons-vibrational-properties-of-crystals). Most likely, something is off with your structure conversion (cartesian vs. direct coordinates maybe?).

@JaGeo so your tip helped me find the source. It wasn't exactly the coordinates, but that the PBC weren't be set for the force calculation. Closing and will post on the mailing list from here on out for usage. Thank you.
