### ISSUE TITLE
Phonopy gruneisen api >  no  option to set filename of yaml files

### ISSUE THREAD

**Issue by naik-aakash** [phonopy/phonopy#336]
# Issue 

Current implementation of gruneisen api does not provide an option to set file name of yaml file saved for mesh and bandstructures. 

# Solution 

Mimic same code as done in phonopy api that allows user to set file names

I will open an PR with this change in next days

**Comment by atztogo** [comment]
@naik-aakash, do you need any help? Probably PhonopyGruneisen needs at least refactoring including adding tests to let it survive longer. It is up to your future plan.

**Comment by naik-aakash** [comment]
Hi @atztogo , thanks! I Will start on the said changes and let you know if I encounter issues and need help 😃 .

Actually, currently we are working on adding a gruneisen workflow to atomate2.
