### ISSUE TITLE
unfolding phonon bandstructure with a vacancy

### ISSUE THREAD

**Issue by rashigeek** [phonopy/phonopy#346]
I am trying to unfold a phonon bandstructure of an h-BN monolayer with a boron vacancy. I have adapted the testing code as follows but I get this error (I am not even considering the defect in the mapping to the perfect supercell yet. I tried that, and I also got the same error):

from phonopy import load
import os
import numpy as np

from phonopy import Phonopy
from phonopy.unfolding.core import Unfolding
from pymatgen.io.vasp import Poscar

yaml_file_path = os.path.join(os.getcwd(), 'phonopy.yaml')

ph = load(yaml_file_path)
ph = ph

high_symmetry_points = {
    'Γ': np.array([0.0, 0.0, 0.0]),
    'K': np.array([0.5, 0.0, 0.0]),
    'M': np.array([0.5, 0.5, 0.0]),
    'X': np.array([0.0, 0.5, 0.0]),
    'S': np.array([0.5, 0.5, 0.5]),
    'Y': np.array([0.0, 0.5, 0.5]),
}

path = ['Γ', 'K', 'M', 'Γ']

num_points_per_segment = 31

qpoints = []

for i in range(len(path)-1):
    start_point = high_symmetry_points[path[i]]
    end_point = high_symmetry_points[path[i+1]]
    # Generate points between start and end, excluding the end point to avoid duplicates
    segment_points = np.linspace(start_point, end_point, num_points_per_segment, endpoint=False)
    qpoints.extend(segment_points)

unfolding_supercell_matrix = np.diag([4, 4, 1])
mapping = np.arange(len(ph.supercell), dtype=int)
mapping
unfolding = Unfolding(
    ph, unfolding_supercell_matrix, ph.supercell.scaled_positions, mapping, qpoints
)
unfolding.run()

-----------------------------------------------------------------------------------------------------------------------

I get the following warning messages and this error:
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-05 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 2 tolerance = 9.025000e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 3 tolerance = 8.573750e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 4 tolerance = 8.145063e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 5 tolerance = 7.737809e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 6 tolerance = 7.350919e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 7 tolerance = 6.983373e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 8 tolerance = 6.634204e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-05 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 2 tolerance = 9.025000e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
...
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 7 tolerance = 6.983373e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/work/spglib/spglib/src/pointgroup.c).
spglib: Attempt 8 tolerance = 6.634204e-06 failed(line 800, /Users/runner/work/spglib/spglib/src/spacegroup.c).

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[5], line 45
     43 mapping = np.arange(len(ph.supercell), dtype=int)
     44 mapping
---> 45 unfolding = Unfolding(
     46     ph, unfolding_supercell_matrix, ph.supercell.scaled_positions, mapping, qpoints
     47 )
     48 unfolding.run()

File ~/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py:141, in Unfolding.__init__(self, phonon, supercell_matrix, ideal_positions, atom_mapping, qpoints)
    [139](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=138) self._atom_mapping = None
    [140](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=139) self._index_map_inv = None
--> [141](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=140) self._set_index_map(atom_mapping)

File ~/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py:285, in Unfolding._set_index_map(self, atom_mapping)
    [283](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=282)         dist = np.sqrt((np.dot(diff, lattice) ** 2).sum(axis=1))
    [284](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=283)         # k is index in _ideal_positions.
--> [285](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=284)         k = np.where(dist < self._symprec)[0][0]
    [286](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=285)         index_map_inv[i, j] = k
    [287](file:///Users/ahmedelrashidy/opt/anaconda3/envs/old_phonopy/lib/python3.8/site-packages/phonopy/unfolding/core.py?line=286) self._index_map_inv = index_map_inv

IndexError: index 0 is out of bounds for axis 0 with size 0

-----------------------------------------------------------------------------------------------------------------------------

However, the same code works for the perfect supercell without any issues. The phonon bandstrcuture of the supercell with the defect has been relaxed and I performed DFPT using VASP. I can get the usual phonon bandstructure without any issues for both supercells. However, unfolding works only for the perfect supercell. Can you please guide me as to what is causing the error? Also, how was the unfolded bandstructure [here](https://iopscience.iop.org/article/10.1088/1361-648X/acd831) generated? Is it possible to provide a sample code of unfolding with a vacancy?

Best,
Ahmed

**Comment by atztogo** [comment]
I don't see the details of your calculation, so I can not answer.

**Comment by rashigeek** [comment]
So as it turns out, the `self._symprec` attribute is too strict if the atoms displace beyond the threshold used, replacing:

`k = np.where(dist < self._symprec)[0][0]`
                    `index_map_inv[i, j] = k`
with:
try:
      k = np.where(dist < self._symprec)[0][0]
      index_map_inv[i, j] = k
except IndexError:
      k = np.argmin(dist)
      index_map_inv[i, j] = k
                index_map_inv[i, j] = k
                
This effectively finds the atom with the smallest distance instead of sticking to the symmetry precision threshold. I am closing this issue. Thank you!

**Comment by rashigeek** [comment]
closed.

**Comment by rashigeek** [comment]
closed
