### ISSUE TITLE
VASP-DFPT & phonopy calculation - Is NSW=1 really necessary?

### ISSUE THREAD

**Issue by TheGreatDeadOne** [phonopy/phonopy#361]
The use of NSW=1 is mentioned in the text, but in the INCAR example the flag is not included.
"
![image](https://github.com/phonopy/phonopy/assets/64573015/cd864326-f898-4fb1-899a-efcffff4bec4)"

**Comment by atztogo** [comment]
Thanks for your catch. I removed NSW=1.
