### ISSUE TITLE
Dynamical matrix may change from numpy 2.0.0

### ISSUE THREAD

**Issue by lan496** [phonopy/phonopy#369]
With the recently released [numpy 2.0.0](https://numpy.org/devdocs/release/2.0.0-notes.html), phonopy sometimes returns a different dynamical matrix with older numpy versions. 

Here is the example with cubic BTO in phonondb (https://mdr.nims.go.jp/download_all/bg257j61f.zip)
The first script saves dynamical matrix array in two numpy versions, 1.26.4 and 2.0.0.
```python
import importlib.metadata
import phonopy
import numpy as np

print(f"{importlib.metadata.version('phonopy')=}")
numpy_version = importlib.metadata.version('numpy')
print(f"{numpy_version=}")

qpoints = [
    ("Gamma", [0, 0, 0]),
    ("X", [0, 0.5, 0]),
    ("M", [0.5, 0.5, 0]),
]

# phonodb-2998 BaTiO3 (Pm-3m)
ph = phonopy.load("BaTiO3/phonopy_params.yaml.xz")
for key, qpoint in qpoints:
    dm = ph.get_dynamical_matrix_at_q(qpoint)
    np.save(f"dm_{key}_{numpy_version}.npy", dm)
```

The second script compares the dynamical matrices.
```python
import numpy as np

qpoints = [
    ("Gamma", [0, 0, 0]),
    ("X", [0, 0.5, 0]),
    ("M", [0.5, 0.5, 0]),
]

def show_diff(key):
    dm1 = np.load(f"dm_{key}_1.26.4.npy")
    dm2 = np.load(f"dm_{key}_2.0.0.npy")
    print(np.max(np.abs(dm1 - dm2)))

for key, _ in qpoints:
    print(key)
    show_diff(key)
```

The second script shows the difference in X and M point dynamical matrices.
```
python compare.py 
Gamma
0.0
X
0.0625670432850866
M
0.06264638894532412
```

### Environment
- Ubuntu 22.04.4 LTS
- Python 3.10.13
- phonopy 2.24.2

**Comment by atztogo** [comment]
Thanks @lan496. How we should proceed migration...

**Comment by atztogo** [comment]
@lan496, could you test by replacing 

https://github.com/phonopy/phonopy/blob/4620e0e1c127f2f8650171f5880a8a72a0e1aff2/phonopy/harmonic/dynamical_matrix.py#L921

by

```python
grid = np.r_["-1,2,0", np.meshgrid(pts, pts, pts)].reshape(3, -1)
```
?

https://numpy.org/doc/stable/reference/generated/numpy.c_.html

**Comment by lan496** [comment]
The discrepancy disappears with the replacement!
Firstly, I have noticed this issue by updating numpy in [spgrep-modulation](https://github.com/phonopy/spgrep-modulation/blob/develop/tests/test_modulation.py) and tested symmetry of dynamical matrices.
This replacement also fixes the error in spgrep-modulation.

**Comment by atztogo** [comment]
Thanks for your test. Then, I will release phonopy with this replacement today.

**Comment by lan496** [comment]
Thank you for your quick fix! I close this issue.
