### ISSUE TITLE
QHA API turns all warnings into errors

### ISSUE THREAD

**Issue by JaGeo** [phonopy/phonopy#380]
This line here https://github.com/phonopy/phonopy/blob/04f912a77e3efbac00a9987b545fc4f5e8927eb9/phonopy/qha/eos.py#L134 turns all warnings into errors. This will affect all subsequent code. 

Could this be made optional in one of the next phonopy versions? I think this is very unsafe once this api is integrated into larger code bases.

(I just spent a longer time debugging to figure out why my code was behaving so strangely)

**Comment by atztogo** [comment]
What is the expected behaviour?

**Comment by JaGeo** [comment]
I would expect that this global warning setting is changed back afterwards

**Comment by atztogo** [comment]
Will inserting `warnings.resetwarnings()` at the last line of `def fit(self, initial_parameters)` fix your issue?

**Comment by JaGeo** [comment]
I will test once I am back. I had used reset to the Default warnings in my code.

**Comment by JaGeo** [comment]
If I use this statement in subsequent code, everything works as expected. Thus, I think inserting the code should work fine. 

I used `warnings.filterwarnings("default")` in my code so far which also seemed to work.

**Comment by atztogo** [comment]
Thank @JaGeo for your checking. I made PR #381. I will merge this if you are fine for this change.

**Comment by JaGeo** [comment]
Thanks! I will close the issue!
