### ISSUE TITLE
2.26 omp_max_threads error

### ISSUE THREAD

**Issue by EricPgh** [phonopy/phonopy#388]
As I was switching to my local linux machine (the HPC is going down for patching), I installed the current (2.26.2) and began receiving an error on phononc.omp_max_threads. Previous version 2.24.3 which I had been using did not have this issue. I reinstalled 2.24.3 and the error went away.

**Comment by atztogo** [comment]
Thanks for your report. I found my mistake. I will release v2.26.3 for the fix.
