### ISSUE TITLE
"Remapping of atoms by TrimmedCell failed." in phonopy/structure/cells.py

### ISSUE THREAD

**Issue by zhangxiaoyu2046** [phonopy/phonopy#389]
Hi all,

When I was calculating a twisted bilayer graphene with phonolammps (version 0.9.2):
$ phonolammps in.lammps --dim 1 1 1 -c POSCAR-unitcell

the dependent package phonopy gives the above error:
  File "/home/wa9055/miniconda3/envs/lammpsAug2023/lib/python3.8/site-packages/phonopy/structure/cells.py", line 784, in _run
    raise RuntimeError("Remapping of atoms by TrimmedCell failed.")
RuntimeError: Remapping of atoms by TrimmedCell failed.

Phonopy version=2.26.0
I had tested several other phonopy versions ( v2.16.3), but it still gives the same error message.
I can't find any problem in the TBG structure, which is already a primitive cell.

Full calculation files are attached below.
Any comments or advice are welcome, thanks!

[phonopy_bug.zip](https://github.com/user-attachments/files/16138989/phonopy_bug.zip)

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
