### ISSUE TITLE
New build system with cmake and nanobind

### ISSUE THREAD

**Issue by ladyteam** [phonopy/phonopy#397]
I'm bit confused with new manual installation of phonopy.  Cmake do compile C code but installation with cmake finished with copying of dynamical libraries. 
Can you please give info how python module should be installed with new build system? 
Thank you in advance.

**Comment by atztogo** [comment]
Hi @ladyteam. It is just like `pip install .`. I tend to use with the editable option, `pip install -e .`. You need a C++ compiler too.
https://phonopy.github.io/phonopy/install.html#building-using-pip-install

**Comment by ladyteam** [comment]
Hi @atztogo, pip in editable mode fails with the following message
``ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /eugene/distrib/phonopy/phonopy-git
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)

In normal mode installation is succesfull (I'm using --prefix tag for installation in desired directory).

I made an empty setup.cfg and run `pip install --prefix=/opt/phonopy-git-new/ -e .` to install phonopy in editable mode again but it fails with errror.
error: Multiple top-level packages discovered in a flat-layout: ['c', 'phonopy'].

I'm using python3.9 and setuptools 71.1.0 all running almalinux 9.3

Not sure if editable mode installation is important for users. I wonder how to pass arguments to cmake build system via pip install. Should I edit [tool.scikit-build.cmake.define] section of pyproject.toml file?

**Comment by atztogo** [comment]
Editable install is an experimental support by scikit-build-core, so it may not work in some environment. Please install without -e option.

> Not sure if editable mode installation is important for users. I wonder how to pass arguments to cmake build system via pip install. Should I edit [tool.scikit-build.cmake.define] section of pyproject.toml file?

No. Probably you have to go into the detail of the sckit-build-core. The build system is fairly complicated and I don't understand the mechanism at all. So my option is just following the rule. Usually editable install is unimportant for most of users.

**Comment by ladyteam** [comment]
Thank you. I agree that build system become really complicated, and it can lead to a mess as in the case of ALM package which seems require mkl library but linking done using symlinks of blas and lapack instead of natural library names (-lmkl_scalapack_lp64 -lmkl_rt and so on). I fianlly fixed issue, so I'll try to creat issue in ALM project with suggested solution.

Is it worth to fix documentation and remove -e option in phonopy documentation?

**Comment by atztogo** [comment]
>Is it worth to fix documentation and remove -e option in phonopy documentation?

True. https://phonopy.github.io/phonopy/install.html#building-using-pip-install

>I'll try to creat issue in ALM project with suggested solution.

Thanks. My colleague and I develop another force constants calculator, https://github.com/symfc/symfc, for which you don't need to compile, though what can be done by it is limited compared with ALM.

**Comment by ladyteam** [comment]
Cool thanks. I made an  issue in ALM project (as mentioned above). I think we can close this issue.
