### ISSUE TITLE
Bug with Phonopy Installation in Python 3.12 Environment

### ISSUE THREAD

**Issue by obaica** [phonopy/phonopy#402]
![image](https://github.com/user-attachments/assets/59655238-d39d-49ef-81a8-44fb1a291db3)

When installing the latest version of Phonopy (version > 2.6) in a Python 3.12 environment, an error occurs preventing the process from completing successfully. The error message indicates an inability to create a process using the specified path, as shown in the attached screenshot.

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
