### ISSUE TITLE
Bug for non-analytic term corrections in phonon/qpoints.py

### ISSUE THREAD

**Issue by nicholascheng94** [phonopy/phonopy#425]
Hi Dr. Togo,

Would like to report a bug for non-analytic term (NAC) corrections in phonon/qpoints.py.

With reference to this report in the mailing list https://sourceforge.net/p/phonopy/mailman/message/36382591/, for a polar material, when I compare with and without NAC on a bands calculation using following `band.conf`
```
DIM = 2 2 2
ATOM_NAME = B N
BAND = AUTO
EIGENVECTORS = .TRUE.
```
running 
```
phonopy --nac band.conf 
grep freq band.yaml | head -12
```
and
```
phonopy band.conf 
grep freq band.yaml | head -12
```
I can observe the LO-TO splitting in mode # 12 where with and without NAC, the phonon frequency differs.

However, if I run a single q-point calculation at Gamma using following `qpoints.conf`
```
DIM = 2 2 2
ATOM_NAME = B N
EIGENVECTORS = .TRUE.
QPOINTS = 0 0 0
FC_SYMMETRY = .TRUE.
NAC = .TRUE.
Q_DIRECTION = 1 1 0 # comment out for no NAC
```
and running following with and without NAC
```
phonopy qpoints.conf 
grep freq qpoints.yaml 
```
with and without NAC, the phonon frequencies are the same.

I traced the code and found in (current develop branch) `phonon/qpoints.py` line 243 that with OpenMP, `self._nac_q_direction` was not passed to `run_dynamical_matrix_solver_c`. Without OpenMP I believe should be no issue, but I did not test it.

Please see the following commit in my forked branch for my fix https://github.com/nicholascheng94/phonopy/commit/2bbcbd2b7944ddf78a50875ad61fd40a2ce79c1f. If no issues, may I open a pull request for this commit?

Thanks!

Nicholas

Inputs: [phonopy-nac-qpoints.zip](https://github.com/user-attachments/files/16990165/phonopy-nac-qpoints.zip)

**Comment by atztogo** [comment]
Bug confirmed. Thanks for your report!
