### ISSUE TITLE
bug in calculating FORCE_CONSTANTS from FORCE_SETS

### ISSUE THREAD

**Issue by SiyuChen** [phonopy/phonopy#440]
Hi, 
I seem to find a bug in calculating FORCE_CONSTANTS from FORCE_SETS. Could you please help me get to the bottom of this? Thank you!

To make things easy, I have made a simplified example for you to reproduce the issue. Please see 
[bug_report2.zip](https://github.com/user-attachments/files/17459485/bug_report2.zip)

Basically, I have a FORCE_SETS as follows:

> 6
> 4
> 
> 1
>   0.0105835442184000   0.0000000000000000   0.0000000000000000
>   -0.4514226300   -0.0350149200   -0.0000109500
>    0.0219721400    0.0177601300    0.0217464200
>    0.0220894700    0.0171402900   -0.0217244100
>    0.1039357900    0.0274433600    0.0248566600
>    0.2017215800   -0.0525131200   -0.0023641600
>    0.1017036500    0.0251842600   -0.0225035500
> 
> 1
>  -0.0105835442184000   0.0000000000000000   0.0000000000000000
>    0.4513936400    0.0349476700   -0.0000142100
>   -0.0221182600   -0.0172074400   -0.0217215000
>   -0.0220016400   -0.0178279000    0.0217424200
>   -0.1016739100   -0.0251168900   -0.0225059300
>   -0.2016933000    0.0525797500   -0.0023624800
>   -0.1039065300   -0.0273751700    0.0248617000
> 
> ...

As you see, I have manually set the displacement along the Cartesian axes (x-direction), such that one can easily work out the force constant matrix by definition. For example:

-(-0.4514226300 - 0.4513936400) / (0.0105835442184000 * 2) = 42.6518872775
-(0.0219721400 - -0.0221182600) / (0.0105835442184000 * 2) = -2.08296951806

The above results are indeed consistent with the first and second blocks in FORCE_CONSTANTS phonopy outputted

> 1 1
>     42.651887277534627     3.305253351630850    -0.000000000000001
>      3.305253351630860    42.651887277534613    -0.000000000000001
>      0.000000000000000    -0.000000000000000    48.898605166713956
> 1 2
>     -2.082986289382442    -1.651992908916403    -2.053535852594157
>     -1.651992908916404    -2.082986289382441    -2.053535852594156
>      2.054116825269578     2.054116825269577    -5.205810205263099
> 1 3
>     -2.082986289382442    -1.651992908916403     2.053535852594157
>     -1.651992908916404    -2.082986289382441     2.053535852594157
>     -2.054116825269578    -2.054116825269577    -5.205810205263099
> 1 4
>    -14.386120741603310     1.240903305073117    -1.118818729874415
>      1.240903305073113   -14.386120741603309    -1.118818729874415
>     -1.118961994736234    -1.118961994736234   -14.689469972612175
> ...
> 

However, the "1 4" block seems to be incorrect. By definition, I expect to obtain  

-(0.1039357900 - -0.1016739100) / (0.0105835442184000 * 2) = -9.71365053885

instead of -14.386120741603310.

**Comment by atztogo** [comment]
Have you take into account of crystal symmetry? The methodological detail is found in the paper https://journals.aps.org/prb/abstract/10.1103/PhysRevB.84.094302.

**Comment by atztogo** [comment]
By not `FC_SYMMETRY=.FALSE.` but `SYMMETRY=.FALSE.`, you can't compute force constants. This means the symmetry of the supercell structure is used to expand information of `FORCE_SETS`. What I meant in the previous comment is that your hand-writing `FORCE_SETS` probably breaks the symmetry of the supercell structure. Then, phonopy tries to compute force constants along with symmetrization, which resulted in disagreement with that you expected by your hand calculation. The detail is written in the paper as given above.

**Comment by SiyuChen** [comment]
Okay, I see your point. Just to clarify:

I didn't make up FORCE_SETS. The FORCE_SETS I provided in the example is not hand-writing --- it is indeed from high-precision DFT calculations of the displaced supercell (and is extracted by phonopy itself from vasprun.mxl), so I don't think FORCE_SETS breaks the symmetry of the supercell structure (within some tolerance of numerical noise).

**Comment by atztogo** [comment]
I realize I misunderstood your point about the `FORCE_SET`. However, I still need more information to fully understand what you're trying to convey. Could you please clarify further? For example, there is no displacement in the y direction in your case. How are you able to compute the corresponding elements? Can you calculate all the elements of the force constants on your own while ensuring the symmetry of the force constants is respected?

Your choice of supercell structure seems unusual, and the point group of the supercell lattice differs from that of the primitive cell:

```
In [1]: import phonopy

In [2]: ph = phonopy.load("phonopy.yaml")
Warning: Point group symmetries of supercell and primitivecell are different.
```

The situation appears to be quite complex, and to be honest, your explanation hasn't fully convinced me yet. Simply computing a few elements doesn't entirely resolve the issue. Symmetrically equivalent elements of the force constants may not have the same values in numerical calculations. In phonopy, these elements are averaged through least-square fitting.  Especially this can happen when the supercell is small. It seems you might not have a complete understanding of the overall process involved in force constants calculation.

Could you share any critical details regarding the bug you believe might be present, especially after reviewing the paper? This could help in clarifying things further.

**Comment by SiyuChen** [comment]
Hi @atztogo, sure, very happy to provide more information and sorry I didn't make things clear enough. Also, thank you very much for your time. Let me first answer your questions and then share more details.

> For example, there is no displacement in the y direction in your case. How are you able to compute the corresponding elements? Can you calculate all the elements of the force constants on your own while ensuring the symmetry of the force constants is respected?

Reply to Q1: y-direction displacement is not necessary because of the site symmetry of the atom. 
Reply to Q2: Yes, I have calculated all the elements of the force constants on my own while ensuring the symmetry of the force constants. It is the disagreement between my results and phonopy's results that made me believe there is probably a bug present.

Now let me clarify why I think FORCE_CONSTANTS is likely incorrect. I will break my argument down into small parts to make sure we understand each other. 

According to the definition of the force constant matrix, the matrix element is given by
```math
\Phi^{x,x}_{1,4} = -dF^{x}_{4}/dr^{x}_{1} ≈ - [F^{x}_{4} (+\Delta r^{x}_{1}) - F^{x}_{4} (-\Delta r^{x}_{1})]  / (2 * \Delta r^{x}_{1})
```
where the superscript (here I explicitly wrote x ) is the Cartesian indices, and the subscript (here I explicitly wrote 1 and 4 ) is the atom indices. 

Do you agree with this equation?



If so, in the FORCE_SETS I have found  
```math
F^{x}_{4} (+\Delta r^{x}_{1}) = 0.1039357900
```
```math
F^{x}_{4} (-\Delta r^{x}_{1}) = -0.1016739100
```
```math
\Delta r^{x}_{1} =0.0105835442184000 
```

Do you agree with the above judgment??



If so, let's substitute them into the equation, I get
```math
\Phi^{x,x}_{1,4}  = -(0.1039357900 - -0.1016739100) / (0.0105835442184000 * 2) = -9.71365053885
```

Do you agree that this should be the right value for $\ \Phi^{x,x}_{1,4} \$?

This above value is inconsistent with the value, -14.386120741603310, which can be found in "1 4"-block in FORCE_CONSTANTS (first row and first column):

> 1 4
> -14.386120741603310 1.240903305073117 -1.118818729874415
> 1.240903305073113 -14.386120741603309 -1.118818729874415
> -1.118961994736234 -1.118961994736234 -14.689469972612175


Hope the above explanation clarifies the things.

**Comment by SiyuChen** [comment]
just in case, here I added the vasprun.xml files from which I obtained the FORCE_SETS, along with other my inputs files:  
[bug_report2.zip](https://github.com/user-attachments/files/17459485/bug_report2.zip)

I confirm all vasprun.xml files are genuine vasp outputs (not hand-writing, no modification, so the obtained force should respect the symmetry of the supercell structure.). The FORCE_SETS is created by `phonopy -f vaspruns/vasprun.xml-00*`. I have also checked the consistency between all POSCAR-00* files, phonopy_disp.yaml and vasprun.xml.

**Comment by atztogo** [comment]
It is not my point. There are symmetrically equivalent elements (or related by symmetry operations) of force constants. But have you gotten them as equivalent (related)?

**Comment by SiyuChen** [comment]
> It is not my point. There are symmetrically equivalent elements (or related by symmetry operations) of force constants. But have you gotten them as equivalent (related)?

Yes, I have

**Comment by atztogo** [comment]
You calculate the force constants using the finite difference method, which means you do not strictly adhere to the formal definition of the force constant matrix. Due to time constraints, I am unable to continue this discussion in depth. If this is indeed a bug, I am unsure how to resolve it. Therefore, I kindly request that you submit a pull request with your proposed fix.

**Comment by SiyuChen** [comment]
I agree with you that force constants using the finite difference method do not strictly adhere to the formal definition of the force constant matrix. However, I still believe this is not the reason for the difference between the values I expected and obtained. In fact, the value -9.7136... indeed appears in some blocks in FORCE_CONSTANTS, for example, the "1-6"-block,

> 1 6
>     -9.713673215563123    -2.483073199081215    -0.000000000000000
>     -2.483073199081217    -9.713673215563123     0.000000000000000
>     -0.000000000000000    -0.000000000000000    -9.108044338531887

Only part of the matrix elements of `FORCE_CONSTANTS' deviate from the values calculated by definition, while the remaining agree with each other very well. Therefore, I think this suggests that the issue is not likely simply caused by numerical noise from the finite difference calculations.

Anyway, thank you very much for your time!

**Comment by atztogo** [comment]
Since I am unable to identify any further issues, I will close this ticket for now. Please feel free to reopen it if needed.
