### ISSUE TITLE
wrong results in irreps.yaml

### ISSUE THREAD

**Issue by asiyeshokri** [phonopy/phonopy#444]
Hello

I use phonopy to get name of frequency modes of my monoclinic structure. I use a primitive cell and do a DFPT (IBRION=8) calculation with vasp; then I get force constants by phonopy and then I set the symm.conf as below and phonopy --readfc --dim="1 1 1" symm.conf. Although it shows correct name of the modes (Au,Bu, Ag and Bg) but the orders are not as I see in all the literature! mode 4 should be Ag but it is Bg, and some other similar flips. Would you please help me understand what is the problem?
symm.conf:
IRREPS = 0 0 0 1e-3
SHOW_IRREPS = .TRUE.

Best regards,
Asiyeh

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
