### ISSUE TITLE
Gruneisen API results different when updating phonopy from v2.27.0 to >=v2.28 

### ISSUE THREAD

**Issue by naik-aakash** [phonopy/phonopy#455]
Dear @atztogo ,

I am using the gruneisen api to compute gruneisen mesh  (20, 20, 20) for Si structure. I have the phonopy.yaml stored from the phonon runs for the ground, shrunk and expanded structures.  
https://github.com/phonopy/phonopy/blob/5be99fd2cb3eb87d5c8d1278b1014be826797794/phonopy/api_gruneisen.py#L41

Below is the code snippet

```python
from phonopy.api_gruneisen import PhonopyGruneisen

gru = PhonopyGruneisen(phonon="ground_phonopy.yaml", phonon_plus="plus_phonopy.yaml", phonon_minus="minus_phonopy.yaml")
gru.set_mesh(
    mesh=(20, 20, 20),
    shift=None,
    is_gamma_center=True,
    is_time_reversal=True,
    is_mesh_symmetry=True)

gru._mesh.write_yaml(filename="gruneisen_mesh.yaml")
```
I noticed when using` v2.27` in the generated gruneisen mesh yamls , the gruneisen values for the first 3 bands at [0, 0 ,0] q-point are in `the range -200`.

But when using any `version >=v.2.28` for the same q-point ([0, 0 ,0]) the gruneisen values for the first 3 band now are in `the range of 19 to 51`.

I am not able to track what exactly changed in the code in the updates. I do not see any changes in the Gruneisen API directly on git history. One commit relating to yaml reading I could see is https://github.com/phonopy/phonopy/commit/c013a1992086eba92e70d9afef8342c225165b4f

Could it be this change is causing the discrepancy in the results observed? 

Thank you for your help in Advance.

I am happy to share the input yaml files if necessary.

**Comment by naik-aakash** [comment]
Dear @atztogo, am adding here the inputs and outputs as well where we can see  the differences I observe using different versions of phonopy for your reference.

## Inputs
[gruneisen_Si_inputs.zip](https://github.com/user-attachments/files/17868226/gruneisen_Si_inputs.zip)

## Outputs from the PhonopyGruneisen with different versions
[grunesien_parameter_checks.zip](https://github.com/user-attachments/files/17868227/grunesien_parameter_checks.zip)

**Comment by atztogo** [comment]
I am not familiar with pymatgen. To make the example as simple as possible for me to understand, please do not use pymatgen in the script.

**Comment by atztogo** [comment]
Oh sorry, this comment was not in this issue, but for #457.

**Comment by atztogo** [comment]
I could not run your snippet.

**Comment by naik-aakash** [comment]
> I could not run your snippet.

this comment is also related to other issue, not this issue I assume.

**Comment by atztogo** [comment]
I could not run your snippet:
```python
from phonopy.api_gruneisen import PhonopyGruneisen

gru = PhonopyGruneisen(phonon="ground_phonopy.yaml", phonon_plus="plus_phonopy.yaml", phonon_minus="minus_phonopy.yaml")
gru.set_mesh(
    mesh=(20, 20, 20),
    shift=None,
    is_gamma_center=True,
    is_time_reversal=True,
    is_mesh_symmetry=True)

gru._mesh.write_yaml(filename="gruneisen_mesh.yaml")
```

**Comment by naik-aakash** [comment]
> I could not run your snippet:
> 
> ```python
> from phonopy.api_gruneisen import PhonopyGruneisen
> 
> gru = PhonopyGruneisen(phonon="ground_phonopy.yaml", phonon_plus="plus_phonopy.yaml", phonon_minus="minus_phonopy.yaml")
> gru.set_mesh(
>     mesh=(20, 20, 20),
>     shift=None,
>     is_gamma_center=True,
>     is_time_reversal=True,
>     is_mesh_symmetry=True)
> 
> gru._mesh.write_yaml(filename="gruneisen_mesh.yaml")
> ```

ops, sorry, seems I missed one step of loading yamls. This should also work now.

```python
import phonopy
from phonopy.api_gruneisen import PhonopyGruneisen

# load the phonopy.yamls
ground = phonopy.load("org/ground_phonopy.yaml")
plus = phonopy.load("plus/plus_phonopy.yaml")
minus = phonopy.load("minus/minus_phonopy.yaml")

gru = PhonopyGruneisen(phonon=ground, phonon_plus=plus, phonon_minus=minus)
gru.set_mesh(
    mesh=(20, 20, 20),
    shift=None,
    is_gamma_center=True,
    is_time_reversal=True,
    is_mesh_symmetry=True)

gru._mesh.write_yaml(filename="gruneisen_mesh.yaml")
```

**Comment by atztogo** [comment]
I could run. 

How can I compare the results in this case? The comment at the top is a bit difficult for me to understand. Could you clarify your issue in a simpler way? For example, you could highlight the differences between the results in a clear and straightforward manner, rather than using lengthy text explanations.

**Comment by naik-aakash** [comment]
Okay, I will try to simplify it. I have added plots I get using two different versions of phonopy with same set of phonopy yaml files 

# when using `v2.27`, the gruneisen values at [0, 0, 0] q-point,

<img width="373" alt="image" src="https://github.com/user-attachments/assets/7412ef6e-4f3e-4a4d-a560-84d49d80a338">

## The gruneisen mesh plot saved, looks like this

<img width="701" alt="image" src="https://github.com/user-attachments/assets/4f3e8137-7786-4d7d-9c3b-c9fe265527c6">


# when using `>=v2.28`, the gruneisen values at [0, 0, 0] q-point,

<img width="400" alt="image" src="https://github.com/user-attachments/assets/f81653db-deb7-455a-9bba-dbf5e30d9ae3">

## The gruneisen mesh plot saved, looks like this


<img width="699" alt="image" src="https://github.com/user-attachments/assets/e252a361-7464-42b2-ab3b-4c21c0e0f750">

**Comment by atztogo** [comment]
As you can see the formula that is implemented in phonopy:

https://phonopy.github.io/phonopy/gruneisen.html#method-to-calculate-mode-gruneisen-parameters

Calculation of Gruneisen parameter tends to be unstable for omega -> 0 (like zero divided by zero). This happens for the acoustic modes at Gamma point. The values you show are those phonons, so I think you can simple ignore them.

**Comment by naik-aakash** [comment]
Dear @atztogo, thank you so much for the explanation. I will close this issue now.
