### ISSUE TITLE
Phonon API for non-symmetrized structures does not work any more

### ISSUE THREAD

**Issue by naik-aakash** [phonopy/phonopy#457]
Dear @atztogo ,

I noticed the Python phonon API does not work anymore since the recent refactoring introduced in v2.30.0 when we try to get force constants for non-symmetrized structures.

It currently fails at this specific step when we try to get force constants from a set of forces , 
https://github.com/phonopy/phonopy/compare/v2.29.0...v2.30.0#diff-31bb43c3e0da9ba28439d5c876da9f2c0a0e811bf21ae802b6f555efb99564d9

I think it fails because this method works only on symmetrized structures. Correct me if am wrong here.

I found simply moving this line below the first if clause, recovers the previous behavior of <=v2.29.0 (not sure if this is the best solution) 

https://github.com/phonopy/phonopy/blob/cf27ef5a8c319edb7b724dd58ffa8d5f4b1059aa/phonopy/interface/fc_calculator.py#L110C5-L110C66

Also I would like to ask would it be possible to have a new version with this fix anytime soon?

**Comment by atztogo** [comment]
@naik-aakash, thanks for your bug report. I will fix it. Could you provide an example that fails?

**Comment by naik-aakash** [comment]
Dear @atztogo, as requested, I have attached a minimal example where I see the failure occurring. I have included a Python script and requirements.txt in this archive that reproduces the issue 

[minimal_example.zip](https://github.com/user-attachments/files/17868176/minimal_example.zip)

**Comment by atztogo** [comment]
I am not familiar with pymatgen. To make the example as simple as possible for me to understand, please do not use pymatgen in the script.

**Comment by naik-aakash** [comment]
Dear @atztogo, really sorry for the inconvenience. I have now updated the script to be independent of pymatgen and uses only phonopy interface with vasp.

```python
import numpy as np
from phonopy.api_phonopy import Phonopy
from phonopy.units import VaspToTHz
from phonopy.interface.vasp import Vasprun, read_vasp

# get forces from vasprun xml 
vasprun = Vasprun(fileptr="phonon_static_1_1/outputs/vasprun.xml")

set_of_forces = [vasprun.read_forces()]
   

# reading the original structure
cell = read_vasp(filename="static/outputs/POSCAR")


phonon = Phonopy(cell, 
                supercell_matrix=[[1, 0, 0], [0, 1, 0], [0, 0, 1]],
                 primitive_matrix="auto",
                 symprec=0.001,
                 factor=VaspToTHz,
                 is_symmetry=True)
                 
phonon.generate_displacements(distance=0.01)

phonon.produce_force_constants(forces=set_of_forces) # failing step with >=v.2.29 (works fine on version v.2.27)
```

**Comment by atztogo** [comment]
It seems, your POSCAR contains 2 atoms, but you have forces of 8 atoms.

**Comment by atztogo** [comment]
I don't get error with
```
supercell_matrix=[[-1, 1, 1], [1, -1, 1], [1, 1, -1]],
```

**Comment by naik-aakash** [comment]
Yes, thanks. The POSCAR contains 2 atoms I agree of the primitive cell. Am bit wondering why it worked without any problems with <=v2.28, even with supercell matrix of [[1, 0, 0], [0, 1, 0], [0, 0, 1]] 

just with never versions it raises error

**Comment by atztogo** [comment]
Now the error is raised as expected, which is the correct behavior. If you are satisfied with this outcome, please feel free to close the issue.

**Comment by naik-aakash** [comment]
thanks @atztogo , yes am happy with it, will close the issue 😃 . Thanks again
