### ISSUE TITLE
Different results between CP2K and VASP

### ISSUE THREAD

**Issue by YuliangS** [phonopy/phonopy#468]
Hi
I used the phonopy to do the phono calculations based on two different interfaces (CP2K and VASP) for the same structure(Mono-layer Ni₃(HIB)₂ (HIB: hexaiminobenzene). But the results are totally different, as the figures shown. The first one is VASP results and second one is CP2K results.
I checked the input files and test the examples, they looks good, only these 2D-layered structures has similar problems.
Could you please help me to understand this problems?

Thank you
![VASP](https://github.com/user-attachments/assets/9b861d1b-cf2f-4de7-9064-ebede7bda55d)
![CP2K](https://github.com/user-attachments/assets/a1148f6e-3306-4561-bfb0-0d9bbe822257)

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.
